### ISSUE TITLE
crash when trying to access replays and the directory doesn't exist

### ISSUE THREAD

**Issue by dyanarose** [HearthSim/Hearthstone-Deck-Tracker#1855]
[12:07:39] LastReplay: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user\AppData\Roaming\HearthstoneDeckTracker\Replays'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.MenuItemReplayLastGame_OnClick(Object sender, RoutedEventArgs e)

https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Windows/MainWindow/MainWindow.xaml.cs#L185

**Comment by Epix37** [comment]
Do you have a crash log? That should log an exception (the one you posted) but not crash the application.

**Comment by dyanarose** [comment]
The above was pulled from the application folder's crash log. Unless I'm misunderstanding of course and I should be looking in a differnet location.

Let me know and I'll post it later on.

**Comment by Epix37** [comment]
The crash logs contain the full log, so this might very well be in the log but not the reason for the crash. Does the application crash when you click "latest replay" without the directory existing?

**Comment by dyanarose** [comment]
yep, that's what prompted me to have a look and these were the last records in the log at that point. If this should only be logging and not crashing, I'll have a look through my system log and see if there's anything to see. I'll get back with any new info this evening.

**Comment by dyanarose** [comment]
this is the only other thing I'm seeing in the logs.

########## 12/12/2015 12:08:02 ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.GameEventHandler.<HandleGameEnd>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

so a trace from the end of the previous game goes:
[12:05:23] HandleGameEnd: Game ended...
[12:05:23] Gamestats: Current Game ended after 10 turns
[12:05:23] HandleGameEnd: Assigned current game to deck: murloc-a-din
[12:05:23] HandleGameEnd: Waiting for game mode detection...
[12:05:34] Game: Set CurrentGameMode to Casual
[12:05:34] HandleGameEnd: Detected game mode, continuing.
[12:05:34] HandleGameEnd: CurrentGameMode=Casual, Waiting for ranked detection...
[12:05:35] HandleInMenu: Game is now in menu.
[12:05:35] HandleInMenu: CurrentGameMode=Casual, Waiting for ranked detection...
[12:06:16] DeckList: Set active deck to: 
[12:06:30] UpdateOverlay: Refreshed overlay topmost status
[12:07:28] LastReplay: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user\AppData\Roaming\HearthstoneDeckTracker\Replays'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.MenuItemReplayLastGame_OnClick(Object sender, RoutedEventArgs e)
[12:07:39] LastReplay: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user\AppData\Roaming\HearthstoneDeckTracker\Replays'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.MenuItemReplayLastGame_OnClick(Object sender, RoutedEventArgs e)
[12:08:01] Tracker: Switched to deck: murloc-a-din
[12:08:01] Game: -------- Reset ---------
[12:08:01] OpponentSecrets: Cleared secrets
[12:08:01] DeckList: Set active deck to: deck (Paladin)
[12:08:02] Game: Set CurrentGameMode to Ranked
[12:08:02] Game: Set CurrentGameMode to Ranked
[12:08:02] GameEventHandler: set rank to 17

**Comment by riQQ** [comment]
Same stack trace as #1595 and #1878, closing as this was likely fixed.
