### ISSUE TITLE
Freezing while Syncing

### ISSUE THREAD

**Issue by Clubrub** [HearthSim/Hearthstone-Deck-Tracker#1940]
```
[3:15:47 AM] DeckList: Set active deck to: Dragon Priest (Priest)
[3:15:48 AM] Tracker: Switched to deck: Dragon Priest
[3:15:48 AM] LogReaderManager: LogReaders could not be stopped, stop already in progress.
[3:15:48 AM] Game: -------- Reset ---------
[3:15:48 AM] Player Name: 
[3:15:48 AM] Opponent Name: 
[3:15:48 AM] OpponentSecrets: Cleared secrets
[3:15:49 AM] GameEventHandler: Reset constructed importing
[3:15:49 AM] BackupManager: Running BackupManager
[3:15:49 AM] BackupManager: Backup for today already exists
[3:15:49 AM] HearthStatsManager: starting sync process: forceFullSync=False, background=True
[3:15:49 AM] HearthStatsManager: background process indicator ON
[3:15:49 AM] HearthStatsManager: Checking HearthStats for new decks...
[3:15:49 AM] HearthStatsManager: trying to download decks
[3:15:49 AM] HearthStatsAPI: getting decks since 1451556305
[3:15:49 AM] PluginManager: Loading Plugins...
[3:15:49 AM] PluginWrapper: Loading Arena Helper
[3:15:49 AM] PluginWrapper: Enabled Arena Helper
[3:15:49 AM] Helper: Checking for LIVE updates...
[3:15:49 AM] Helper: Current version: 0.13.7.0
[3:15:49 AM] LogReader: Current region: US
[3:15:49 AM] UpdateOverlay: Refreshed overlay topmost status
[3:15:49 AM] GameEventHandler: Reset constructed importing
[3:15:49 AM] Helper: Latest LIVE version: 0.13.7.0
[3:15:49 AM] HearthStatsManager: no new decks
[3:15:49 AM] HearthStatsManager: Checking HearthStats for new matches...
[3:15:49 AM] HearthStatsManager: trying to download games
[3:15:49 AM] HearthStatsAPI: getting games since 1451556305
[3:15:50 AM] HearthStatsManager: no new games
[3:15:50 AM] HearthStatsManager: Checking for new local decks...
[3:15:50 AM] HearthStatsManager: Checking for new local versions...
[3:15:50 AM] HearthStatsManager: Checking for edited local decks...
[3:15:50 AM] HearthStatsManager: Checking for new local matches...
[3:15:50 AM] HearthStatsManager: Uploading 65 new matches...
[3:15:50 AM] HearthStatsManager: trying to upload 1 matches for deck Zoolock
[3:15:50 AM] HearthStatsManager: trying to upload 1 matches for deck Handlock
[3:15:50 AM] HearthStatsManager: trying to upload 1 matches for deck Totem Shaman
[3:15:50 AM] HearthStatsManager: trying to upload 2 matches for deck Fatigue Warrior
[3:15:50 AM] HearthStatsManager: trying to upload 3 matches for deck Grim Patron
[3:15:50 AM] HearthStatsManager: trying to upload 1 matches for deck Demon Handlock
[3:15:50 AM] HearthStatsManager: trying to upload 5 matches for deck Control Priest
[3:15:50 AM] HearthStatsManager: trying to upload 2 matches for deck Midrange Druid
[3:15:50 AM] HearthStatsAPI: Game Loss vs Warrior, 8/8/2015 11:19:32 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Loss vs Mage, 9/28/2015 4:07:23 PM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Loss vs Warrior, 9/29/2015 8:02:11 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Loss vs Druid, 7/15/2015 11:19:04 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Loss vs Mage, 7/15/2015 11:29:32 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Loss vs Warrior, 9/29/2015 8:02:11 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Loss vs Priest, 7/15/2015 12:00:06 PM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsManager: No valid games
[3:15:50 AM] HearthStatsManager: trying to upload 1 matches for deck Mid-Range Pally
[3:15:50 AM] HearthStatsAPI: Game Win vs Warrior, 9/21/2015 3:32:43 PM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsManager: No valid games
[3:15:50 AM] HearthStatsManager: trying to upload 5 matches for deck Mid-Range Pally
[3:15:50 AM] HearthStatsAPI: Game Win vs Mage, 10/9/2015 9:29:27 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Win vs Warlock, 10/10/2015 1:08:16 PM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Win vs Druid, 10/12/2015 5:12:22 PM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Loss vs Paladin, 10/14/2015 11:34:43 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Loss vs Paladin, 10/14/2015 11:41:09 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsManager: No valid games
[3:15:50 AM] HearthStatsManager: trying to upload 2 matches for deck Raptor Rogue
[3:15:50 AM] HearthStatsAPI: Game Win vs Mage, 8/8/2015 11:32:22 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsManager: No valid games
[3:15:50 AM] HearthStatsAPI: Game Win vs Mage, 9/4/2015 12:23:32 PM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsManager: No valid games
[3:15:50 AM] HearthStatsManager: trying to upload 18 matches for deck Entomb Priest
[3:15:50 AM] HearthStatsAPI: Game Win vs Druid, 12/9/2015 9:48:35 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Loss vs Warrior, 9/29/2015 8:03:23 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Loss vs Warrior, 9/29/2015 8:03:23 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Win vs Hunter, 12/13/2015 12:06:12 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Loss vs Hunter, 10/27/2015 12:51:59 PM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Loss vs Druid, 10/29/2015 6:27:24 PM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsManager: No valid games
[3:15:50 AM] HearthStatsAPI: Game Loss vs Warlock, 12/2/2015 9:35:01 PM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsManager: trying to upload 1 matches for deck Murloc Shaman
[3:15:50 AM] HearthStatsAPI: Game Loss vs , 12/2/2015 9:47:27 PM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsManager: No valid games
[3:15:50 AM] HearthStatsManager: trying to upload 2 matches for deck Aggro Shaman
[3:15:50 AM] HearthStatsAPI: Game Loss vs Shaman, 12/6/2015 9:27:33 PM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Loss vs Druid, 12/7/2015 7:50:36 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsManager: No valid games
[3:15:50 AM] HearthStatsManager: trying to upload 1 matches for deck Reno Handlock
[3:15:50 AM] HearthStatsAPI: Game Loss vs Hunter, 12/11/2015 11:07:51 PM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsManager: No valid games
[3:15:50 AM] HearthStatsAPI: Game Loss vs Druid, 12/4/2015 6:14:33 PM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsManager: No valid games
[3:15:50 AM] HearthStatsAPI: Game Loss vs Mage, 11/11/2015 10:44:26 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsManager: No valid games
[3:15:50 AM] HearthStatsManager: No valid games
[3:15:50 AM] HearthStatsManager: trying to upload 2 matches for deck Tempo Mage
[3:15:50 AM] HearthStatsAPI: Game Win vs Paladin, 9/23/2015 10:15:25 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsAPI: Game Loss vs Paladin, 9/29/2015 5:24:00 PM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsManager: No valid games
[3:15:50 AM] HearthStatsAPI: Game Win vs Warrior, 12/11/2015 12:00:44 AM is not valid (invalid game mode: None)
[3:15:50 AM] HearthStatsManager: No valid games
[3:15:50 AM] : Some error occoured, main status=400
[3:15:50 AM] HearthStatsAPI: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object , Int32 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Hearthstone_Deck_Tracker.HearthStats.API.HearthStatsAPI.<PostMultipleGameResultsAsync>d__1.MoveNext()
[3:15:51 AM] : Some error occoured, main status=400
[3:15:51 AM] HearthStatsAPI: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object , Int32 )
   at Hearthstone_Deck_Tracker.HearthStats.API.HearthStatsAPI.<PostMultipleGameResultsAsync>d__1.MoveNext()
[3:15:51 AM] HearthStatsManager: background process indicator OFF
[3:15:51 AM] HearthStatsManager: finished sync process
```

**Comment by Clubrub** [comment]
![untitled](https://cloud.githubusercontent.com/assets/15803410/12067419/f5805f6e-afb6-11e5-8bf8-f15edf98d72c.png)

**Comment by Clubrub** [comment]
![untitled2](https://cloud.githubusercontent.com/assets/15803410/12067432/fefc965c-afb6-11e5-9753-81fd6386dbf5.png)

**Comment by Clubrub** [comment]
[Crash report 31122015-123.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/75705/Crash.report.31122015-123.txt)

**Comment by Clubrub** [comment]
Anything on this?

**Comment by judge2020** [comment]
HearthStats is no longer supported by HDT, a new synchronization system is planned for HSReplay.
