### ISSUE TITLE
need help  Crash report

### ISSUE THREAD

**Issue by qwerTTone** [HearthSim/Hearthstone-Deck-Tracker#2483]
########## 08.05.2016 15:50:20 ##########
System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.IAsyncStateMachine' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Hearthstone_Deck_Tracker.Utility.LogConfig.LogConfigUpdater.Run()
   at Hearthstone_Deck_Tracker.Core.Initialize()
   at Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
Make sure you have .NET Framework 4.5 installed. Reinstall it if you do.

**Comment by qwerTTone** [comment]
Everything works, thank you

**Comment by Epix37** [comment]
:+1:
