### ISSUE TITLE
HS Deck Tracker crash report

### ISSUE THREAD

**Issue by Kryai** [HearthSim/Hearthstone-Deck-Tracker#2520]
I've set up my HS Deck Tracker to use the same data directory/config for 2 different computers, sitting on a samba share. I got it working earlier this week, but now when I start HSDT it crashes immediately on 1 computer. The other PC launches normally. I do not try to launch HSDT while the other PC is already running HSDT. Can I provide more info to help troubleshoot?
Here's the crash log:

`########## 5/21/2016 11:50:51 AM ##########
System.Windows.Markup.XamlParseException: Set property 'System.Windows.FrameworkTemplate.Template' threw an exception. ---> System.BadImageFormatException: [C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll] The signature is incorrect.
   at System.Xaml.Schema.Reflector.GetAttribute(Type attributeType)
   at System.Xaml.Schema.Reflector.GetAttributeString(Type attributeType, Boolean& checkedInherited)
   at System.Xaml.XamlType.TryGetAttributeString(Type attributeType, String& result)
   at System.Xaml.XamlType.LookupAliasedProperty(XamlDirective directive)
   at System.Xaml.XamlType.GetAliasedProperty(XamlDirective directive)
   at System.Windows.FrameworkTemplate.IsNameProperty(XamlMember member, XamlType owner)
   at System.Windows.TemplateContent.ParseNode(XamlReader xamlReader, StackOfFrames stack, List1 sharedProperties, Int32& nameNumber, Object& newValue)
   at System.Windows.TemplateContent.ParseNodes(StackOfFrames stack, List1 sharedProperties, Int32& nameNumber)
   at System.Windows.TemplateContent.ParseTree(StackOfFrames stack, List1 sharedProperties, Int32& nameNumber)
   at System.Windows.TemplateContent.ParseXaml()
   at System.Windows.FrameworkTemplate.set_Template(TemplateContent value)
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_FrameworkTemplate_Template>b__277_0(Object target, Object value)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.InitializeComponent()
   at Hearthstone_Deck_Tracker.Windows.MainWindow..ctor()
   at Hearthstone_Deck_Tracker.Core.Initialize()
   at Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by Epix37** [comment]
Try reinstalling .NET Framework 4.5.

**Comment by Kryai** [comment]
I think you are right. I'm going to reinstall the whole OS on this PC. I think my kid has been messing around and just trashing the base OS. I'll close this and re-open this if after I clean up that box I get the same issue.

**Comment by Kryai** [comment]
Well to put an end to the issue, it turns out this was all due to a failing stick of RAM, that corrupted the .Net installation - my kid was innocent.
