### ISSUE TITLE
Crash 05-30-16. Crashes everytime I launch hearthstone client from bnet

### ISSUE THREAD

**Issue by dukedurl** [HearthSim/Hearthstone-Deck-Tracker#2548]
Hi.  I start deck tracker and launch hearthstone from the bnet client.  deck tracker crashes.  If I launch hearthstone and then from in game launch deck tracker it crashes as well.  please help. ty

```
########## 5/30/2016 10:06:03 PM ##########
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at HearthMirror.ProcessView..ctor(Process proc)
   at HearthMirror.Mirror.get_View()
   at HearthMirror.Reflection.TryGetInternal[T](Func`1 action, Boolean clearCache)
   at HearthMirror.Reflection.IsSpectating()
   at Hearthstone_Deck_Tracker.Hearthstone.GameV2.get_Spectator()
   at Hearthstone_Deck_Tracker.Hearthstone.GameV2.get_CurrentGameMode()
   at Hearthstone_Deck_Tracker.Windows.OverlayWindow.<UpdatePosition>d__91.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
10:05:53 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
10:05:54 PM|Info|MainWindow.SelectDeck >> Switched to deck: MidrangeShaman (v1.1)
10:05:54 PM|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.
10:05:54 PM|Info|GameV2.Reset >> -------- Reset ---------
10:05:54 PM|Info|Player.Name >> [Player] 
10:05:54 PM|Info|Player.Name >> [Opponent] 
10:05:54 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
10:05:54 PM|Info|BackupManager.Run >> Running BackupManager
10:05:54 PM|Info|BackupManager.Run >> Backup for today already exists
10:05:54 PM|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: Checking for updates (current=0.15.1.0, pre-release=False)
10:05:55 PM|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: We are up-to-date (latest=v0.15.1, pre-release=False)
10:05:57 PM|Info|MainWindow.SelectDeck >> Switched to deck: Zoolock (v1.1)
10:05:57 PM|Info|DeckList.ActiveDeck >> Set active deck to: Zoolock (Warlock)
10:05:58 PM|Info|LogReaderManager.Stop >> Stopped LogReaders.
10:05:58 PM|Info|GameV2.Reset >> -------- Reset ---------
10:05:58 PM|Info|Player.Name >> [Player] 
10:05:58 PM|Info|Player.Name >> [Opponent] 
10:05:58 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
10:05:59 PM|Info|LogReaderManager.Restart >> Restarting LogReaders.
```

**Comment by jleclanche** [comment]
Same issue as #2543, which will be fixed in an upcoming release.

You're most likely running Battle.net as Administrator. This is a bad idea. Run Battle.net as a regular user. Failing that, running HDT as Administrator will fix it.

**Comment by dukedurl** [comment]
Hi I ran HDT as administrator and it fixed the problem.  Thank you for responding so quickly
