### ISSUE TITLE
NullReferenceException on spectate end

### ISSUE THREAD

**Issue by belk** [HearthSim/Hearthstone-Deck-Tracker#2602]
Crashed with a NullReferenceException when a game ended while spectating a friend.  Didn't see any similar recent issues.

Crash report log

```
11:55:08 AM|Info|GameEventHandler.HandleTurnStart >> --- Player turn 13 ---
11:55:08 AM|Info|Player.Draw >> [Player] id=24, cardId=BRM_028, cardName=Emperor Thaurissan, zonePos=6,Info={turn=13, originalZone=DECK}
11:55:16 AM|Info|GameEventHandler.HandleLoss >> --- Game was lost! ---
11:55:16 AM|Info|TurnTimer.Stop >> Stopping turn timer
11:55:16 AM|Info|GameEventHandler.HandleGameEnd >> Game ended...
11:55:16 AM|Info|GameEventHandler.HandleGameEnd >> Format: Standard
########## 6/12/2016 11:55:17 AM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.GameEventHandler.<HandleGameEnd>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

hdt_log around that time

```
11:55:08 AM|Info|Player.Draw >> [Player] id=24, cardId=BRM_028, cardName=Emperor Thaurissan, zonePos=6,Info={turn=13, originalZone=DECK}
11:55:16 AM|Info|GameEventHandler.HandleLoss >> --- Game was lost! ---
11:55:16 AM|Info|TurnTimer.Stop >> Stopping turn timer
11:55:16 AM|Info|GameEventHandler.HandleGameEnd >> Game ended...
11:55:16 AM|Info|GameEventHandler.HandleGameEnd >> Format: Standard
11:55:22 AM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
11:55:28 AM|Warning|GameEventHandler.HandleGameEnd >> HandleGameEnd was already called.
11:55:28 AM|Info|GameV2.CurrentMode >> HUB
11:55:28 AM|Info|GameEventHandler.HandleInMenu >> Game is now in menu.
11:55:28 AM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
11:55:28 AM|Info|GameResultNotificationWindow..ctor >> Now showing
11:55:28 AM|Info|GameEventHandler.SaveAndUpdateStats >> Saving DefaultDeckStats
11:55:45 AM|Info|GameEventHandler.HandleGameStart >> --- Game start ---
11:55:45 AM|Info|GameV2.Reset >> -------- Reset ---------
11:55:45 AM|Info|Player.Name >> [Player] 
11:55:45 AM|Info|Player.Name >> [Opponent] 
11:55:45 AM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
11:55:45 AM|Info|TurnTimer.Start >> Starting turn timer
11:55:45 AM|Warning|TurnTimer.Start >> Waiting for player entity
11:55:46 AM|Warning|PowerHandler.Handle >> Could not determine players by checking for opponent hand.
11:55:46 AM|Warning|PowerHandler.Handle >> Could not determine players by checking for player hand either... waiting for draws...
11:55:46 AM|Info|GameEventHandler.TurnStart >> --- Mulligan ---
11:55:46 AM|Info|Player.CreateInPlay >> [Player] id=1, cardId=, cardName=, zonePos=0,Info={turn=0, mark=Created, created=true, originalZone=PLAY}
```

**Comment by mikler** [comment]
@azeier if your commit made it to master can you please resolve/close this issue.

**Comment by riQQ** [comment]
This was probably fixed as there are no similar known issues.
