### ISSUE TITLE
Unable to login with hearthstats

### ISSUE THREAD

**Issue by codeCompositor** [HearthSim/Hearthstone-Deck-Tracker#2609]
Whenever I try to login I get an error: 

```Could not load file or assembly 'System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies```

Report log:

```
9:13:32|Error|HearthStatsAPI.LoginAsync >> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Не удается найти указанный файл.
File name: 'System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
    at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
    at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
    at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
    at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
    at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
    at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
    at Hearthstone_Deck_Tracker.HearthStats.API.HearthStatsAPI.<LoginAsync>d__12.MoveNext() 
```

The problem seems to be here: [link](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/HearthStats/API/HearthStatsAPI.cs#L95)

I also found some usefull information on how to solve this: [link](https://social.msdn.microsoft.com/Forums/vstudio/en-US/dc6d8d89-6fb2-43b6-bf25-40637e4db634/error-reference-required-to-assembly-systemruntimeserialization-version4000?forum=wfprerelease)

>  you simply need to add this attribute to the activity element at the top of the XAML file that gets generated during add service reference.
`xmlns:srs="clr-namespace:System.Runtime.Serialization;assembly=System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"`

I'd be really grateful if you fix this.

**Comment by Epix37** [comment]
Try re-installing .Net Framework 4.5.
