### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by ScottAllen11** [HearthSim/Hearthstone-Deck-Tracker#2626]
Creating temp file directory
Downloading latest version... 23210/23210KB (100%)
Extracting files...
System.AggregateException: One or more errors occurred. ---> System.Exception: Error extracting the downloaded file. ---> System.IO.IOException: The file 'HDTUpdate_new.exe' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at HDTUpdate.Program.CopyFiles(String dir, String newPath)
   at HDTUpdate.Program.<Update>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at HDTUpdate.Program.<Update>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at HDTUpdate.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Error extracting the downloaded file. ---> System.IO.IOException: The file 'HDTUpdate_new.exe' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at HDTUpdate.Program.CopyFiles(String dir, String newPath)
   at HDTUpdate.Program.<Update>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at HDTUpdate.Program.<Update>d__2.MoveNext()<---

There was an error installing the latest update. Press any key to open the website for manual download.

**Comment by Epix37** [comment]
Try deleting the `HDTUpdate_new.exe` and `HDTUpdate.exe`, then download and manually overwrite the files with the latest version: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/tag/v0.15.6

**Comment by ScottAllen11** [comment]
Resolved.
