### ISSUE TITLE
Crash on start since last update

### ISSUE THREAD

**Issue by Herya** [HearthSim/Hearthstone-Deck-Tracker#2682]
Hey,

Since the last update I now have a crash each time i start it, even in admin.

Log here :

`System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'Hearthstone_Deck_Tracker.FlyoutControls.OptionsMain' that matches the specified binding constraints threw an exception. ---> System.TypeInitializationException: The type initializer for 'Hearthstone_Deck_Tracker.Helper' threw an exception. ---> System.BadImageFormatException: Could not load file or assembly 'HearthDb, Version=5.2.0.13619, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
   at Hearthstone_Deck_Tracker.Helper..cctor()
   --- End of inner exception stack trace ---
   at Hearthstone_Deck_Tracker.Helper.set_OptionsMain(OptionsMain value)
   at Hearthstone_Deck_Tracker.FlyoutControls.OptionsMain..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.InitializeComponent()
   at Hearthstone_Deck_Tracker.Windows.MainWindow..ctor()
   at Hearthstone_Deck_Tracker.Core.Initialize()
   at Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

Thanks.

**Comment by riQQ** [comment]
May be issue #2672.

**Comment by Epix37** [comment]
Please try if this 32bit build solves the issue for you: https://github.com/Epix37/HDT-Test/releases/tag/v0.15.10.x86

**Comment by Herya** [comment]
Yes this one can start, thx.
