### ISSUE TITLE
Crashes every time I try to open

### ISSUE THREAD

**Issue by ABRHTTR** [HearthSim/Hearthstone-Deck-Tracker#2719]
So I'm having an issue with Hearthstone Deck Tracker that just started today when I tried to open it up. I am getting an error. The message I get says: "Error: Error restoring PlayerDecks backup. Please manually rename. This is the crash report.

########## 7/31/2016 4:35:14 AM ##########
System.Exception: Error restoring PlayerDecks backup. Please manually rename "PlayerDecks_backup.xml" to "PlayerDecks.xml" in "%appdata\HearthstoneDeckTracker". ---> System.InvalidOperationException: There is an error in XML document (17306, 10). ---> System.Xml.XmlException: Unexpected end of file while parsing Name has occurred. Line 17306, position 10.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.ReadElementString()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckList.Read2_Card(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckList.Read9_Deck(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckList.Read11_DeckList(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckList.Read12_Decks()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Hearthstone_Deck_Tracker.XmlManager`1.Load(String path)
   at Hearthstone_Deck_Tracker.DeckList.Load()
   --- End of inner exception stack trace ---
   at Hearthstone_Deck_Tracker.DeckList.Load()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Hearthstone_Deck_Tracker.Windows.MainWindow.get_IntroductionLabelVisibility()
4:34:10 AM|Info|OverlayWindow.Update >> Refreshed overlay topmost status

It seems straight forward enough so I went into my appdata folder and renamed the file named "PlayerDecks_backup0" however there was already a file named "PlayerDecks.xml". Even after doing so the crash continues to occur.Also there files named "PlayerDecks_corrupted_1" numbered 1 through 11. I am unable to open HDTHelper or HDTUpdate. Also when I open HDTUninstaller the AutoStartEntry is green and says removed if that helps at all. No idea what is wrong. I do know when I opened battle.net today for some reason I had to relocate the location of my game files on my hard drive. That may be what caused the problem originally. Thanks in advance for anyone who knows how to fix this.

-Daniel

**Comment by azeier** [comment]
Try replacing the `PlayerDeck.xml` with the one form the latest backup in `%AppData%/HearthstoneDeckTracker/Backups`.

**Comment by azeier** [comment]
No problem!

The next hdt release will now also do this automatically, should that happen.
