### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by Minitrees** [HearthSim/Hearthstone-Deck-Tracker#2737]
########## 07-Aug-16 1:04:23 PM ##########
System.IO.FileNotFoundException: Could not find file 'C:\Users\Lewis\AppData\Roaming\HearthstoneDeckTracker\config.xml'.
File name: 'C:\Users\Lewis\AppData\Roaming\HearthstoneDeckTracker\config.xml'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Hearthstone_Deck_Tracker.Config.Load()
   at Hearthstone_Deck_Tracker.Core.<Initialize>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by azeier** [comment]
Are you on the latest release (1.0.4)?

Try deleting all `config*.xml` files under `C:\Users\Lewis\AppData\Roaming\HearthstoneDeckTracker`

**Comment by Minitrees** [comment]
If I delete it, it launches fine but if I close it and launch again it gets the same error and renames config.xml into config.xml131151545005493151. And yes, I am on a fresh install of 1.0.4.

**Comment by azeier** [comment]
Do you happen to have a config file in the HDT install dir as well? If so, try deleting both.

**Comment by Minitrees** [comment]
Here's the steps of what happens.
-I delete all config.xml's
-Launches correctly
-I close and try to launch again
-It changes config.xml into config.xml with a set of numbers on the end, different each time.
-Sends Crash Report.
-If I delete that config.xml it sends this crash report:
`System.IO.FileNotFoundException: Could not find file 'C:\Users\Lewis\AppData\Roaming\HearthstoneDeckTracker\PlayerDecks.xml'.
File name: 'C:\Users\Lewis\AppData\Roaming\HearthstoneDeckTracker\PlayerDecks.xml'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Hearthstone_Deck_Tracker.DeckList.SetupDeckListFile()
   at Hearthstone_Deck_Tracker.DeckList.Load()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Hearthstone_Deck_Tracker.Windows.OverlayWindow.SetDeckTitle()
   at Hearthstone_Deck_Tracker.Windows.OverlayWindow.Update(Boolean refresh)
   at Hearthstone_Deck_Tracker.Windows.OverlayWindow..ctor(GameV2 game)
   at Hearthstone_Deck_Tracker.Core.get_Overlay()
   at Hearthstone_Deck_Tracker.FlyoutControls.Options.Overlay.OverlayOpponent.Load(GameV2 game)
   at Hearthstone_Deck_Tracker.FlyoutControls.OptionsMain.Load(GameV2 game)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.LoadConfigSettings()
   at Hearthstone_Deck_Tracker.Core.<Initialize>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by azeier** [comment]
Try installing HDT using the new installer: https://github.com/HearthSim/HDT-Releases/releases/download/v1.0.4/HDT-Installer.exe

**Comment by Minitrees** [comment]
It works now, thanks!
