### ISSUE TITLE
Uneven permissions

### ISSUE THREAD

**Issue by curt1ce** [HearthSim/Hearthstone-Deck-Tracker#2738]
I never had this issue till the latest update I just downloaded. 
![image](https://cloud.githubusercontent.com/assets/235410/17544740/c7280a38-5ee1-11e6-88fb-9251a796d8b4.png)

That is the error message I keep on receiving. I tried everything it says there and still can't fix the problem. Any and all help is greatly appreciated. Thanks

**Comment by azeier** [comment]
Maybe try reinstalling HDT (https://hsdecktracker.net). 

Did anything on your machine change? New users added, windows updates, etc since it worked?

**Comment by Psycho58** [comment]
Hey,
Same problem here, since the last patch keep showing the same message.
Sometimes it works, I don't know why, but 90% of the time the error shows.
I tried every combination to make it work but nothing.
Thanks and hope you can find the solution

**Comment by Psycho58** [comment]
Me again,
I have also some problems with another lay-out program (Overwolf / Heartharena) that won't appear on game and I cannot open it on game. Could it be a problem from Blizzard (I doubt it, because every one will have the same problem) or me and curt1ce and maybe others have exactly the same problem.
Thanks

**Comment by curt1ce** [comment]
I have already tried reinstalling it multiple times to no avail. I can't even get mine to work at all. It says that error message every single time. Also, nothing has changed on my PC. I have the same everything from the last time HDT worked.

**Comment by azeier** [comment]
Two things you could try:

- Set your account to (non-)administrator - depending on what it currently is.
- See if reinstalling Hearthstone helps.

**Comment by Psycho58** [comment]
Hey,
I tried both things you said but didn't work. however I have probably found the solution.
Try to launch Battle.net in administrator mode, than launch Hearthstone from battle.net, and finally launch in administrator mode the Hearthstone tracker. It worked for me.
Hope it will work the other times as well.
Thanks

**Comment by curt1ce** [comment]
I tried another account and reinstalling and tried what Psycho58 said multiple times already and still can't get it to work. Any other possible solutions?

**Comment by TheSaintBol** [comment]
same issue here tried reinstall HS and HDT

**Comment by gendalv** [comment]
1.1.1 started to get this issue

**Comment by blaice** [comment]
I am having the same issue.  Not only did 1.1.1 fail to update automatically, but when I installed it, it completely shat on what was once a good app.  The app is so buggy and unstable now it is unbearable.  I can't even use it anymore.  FULL uninstall more than 3 times, tried running EVERYthing as admin and not and back and etc.  Making your app unusable is not intuitive.  I liked it a lot before.  Too bad.  Gotta look for a new one now.

**Comment by azeier** [comment]
What do you mean by "before"? HDT has not changed much in a long time.

**Comment by blaice** [comment]
The version before 1.1.1 is what I mean by "changed." As an update is a literal inclusion of the definition change, as in changing from previous build?  The previous build is better is what I'm implying, and 1.1.1 is regression at it's finest.

**Comment by blaice** [comment]
The website also does not enable previous builds to be accessed, so my only access is to a dysfunctional version.  Otherwise I would download the previous working version again.

**Comment by jleclanche** [comment]
@blaice Uneven permissions means you are not running HDT and Hearthstone (usually, the Battle.net launcher) as the same user. Usually, that means you're running the Battle.net launcher as admin.

Previous builds can be accessed from the Github releases list (older releases). But I would instead highly recommend you fix how you are running Battle.net / Hearthstone, because this is usually a source of other potential issues. We see it a lot with users who previously tried to work around Battle.net bugs by running it as admin and leave it like that.

**Comment by blaice** [comment]
@jleclanche I am sorry you believe I am inept, but not only did I change the compatibility for bnet launcher, hearthstone, and the deck tracker, but I also tried changing the compatibility for all three in the roaming app data section—and it has made literally no difference.  It works when I first install it maybe a couple times at max, then continues not to work for the next dozen or more times I try it (this is without changing anything).  Thanks for the info about older releases though; I will look into downloading the previous version and see if it rectifies this new problem.

**Comment by jleclanche** [comment]
@blaice I didn't say anything like that, and I get that you're upset but I'd really like it if you toned down the hostility. Both @azeier and I are trying to help you fix this.

Previous releases are here (most recent first): https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases

If you're willing to debug this further, I'd recommend starting with the task manager (running as admin) and taking a look at which process is owned by which user. If you can confirm that both HDT and Battle.net are correctly running as the same user, then this could be a different issue.

**Comment by blaice** [comment]
@jleclanche There are like 4 different access points to bnet launchers though for some reason unbeknownst to me.  Blizzard I guess.  I will also try changing compat for those as well.  So far, it has seemed to help.  I'll see as I try to use it a few more times, but I had to change compat for literally 4 different bnet access points....

**Comment by jleclanche** [comment]
Yes, the Battle.net launcher itself has an "agent" background process and further subprocesses the apps it launches. It's a tangled mess.

**Comment by blaice** [comment]
@jleclanche  Apologies if you sensed hostility, but the tone is hard to tell in text.  I appreciate the help, was just frustrated I changed nothing, yet it stopped working.  Will see if it stays working.

**Comment by blaice** [comment]
@jleclanche problem still persists. No fix.

**Comment by KuriousG** [comment]
As many people have stated above. I've done everything already listed and im also having the same problem.

**Comment by Demonsuji** [comment]
Thanks for adding me to this thread.  What's the best way to be notified of news related to these issues?

**Comment by azeier** [comment]
@Demonsuji Github should automatically subscribe you to issues you comment on. Otherwise you can find the button for it on the right.

**Comment by azeier** [comment]
Can someone get me the HDT log from a session where this happens?
- Start HDT
- Start Hearthstone
- Get error message
- See here for how to find the log: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by nicoell** [comment]
Ran into this problem too, here's the HDT log.
http://pastebin.com/1HX5qav9

**Comment by MikeMNN** [comment]
Also attaching my logs
[hdt_log_1483779284.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/691389/hdt_log_1483779284.txt)
But even without attaching, can say, that you have Win Api issures. I had same problems in C++ few time ago, but it is too hard to remember, what solution I had found.. Problem also was in snapshoting processes and trying to get their info. One thing I can tell you confidently, solution was found a nd it was in another WinApi functions for working with processes. Not sure, that in C# there same methods, but think it would be stupid from Microsoft make it only for one language

**Comment by azeier** [comment]
In both cases the issue (at least after running HDT as admin) seems to be: `System.ComponentModel.Win32Exception (0x80004005): A 32 bit processes cannot access modules of a 64 bit process.`

However, Hearthstone *should* be a 32 bit process. Maybe this is a detection issue of some kind? 
Can you guys check your task manager for whether Hearthstone is actually running as 64 bit?

**Comment by MikeMNN** [comment]
No, Hearthstone is 32 bit executable, I have checked it. But problem sounds in conclusion like this: you trying to access process monitor to get process info, but in further Win versions this monitor is 64 bit. I tryed to fix it in code or find another ways to do this, but there is no part of the source in repository that contains error. If I'm not wrong it is "Mirror" project

**Comment by MikeMNN** [comment]
" Win versions this monitor is 64 bit" Thats not a 100% information, but as I remember my problem in application, that was close to this

**Comment by azeier** [comment]
You can find the source and specifically that part of the code [here](https://github.com/HearthSim/HearthMirror/blob/master/HearthMirror/Status.cs#L27) and [here](https://github.com/HearthSim/HearthMirror/blob/master/HearthMirror/Mirror.cs#L14).

It seems to be a very edge case-y problem (I am not able to reproduce it and it's working fine for thousands of users). 
I would be extremely grateful if you managed to figure out why this is not working on your system!

**Comment by MikeMNN** [comment]
Ok, I''ll look in code and try to find a problem, but can't promise you fast solution - my own work take alot of time, but I will try, and in success case write you

**Comment by azeier** [comment]
Absolutely, no problem. Thank you for taking a look!

**Comment by quack1** [comment]
Don't know if a workaround has been found for this, but I encounter this issue from time to time.
For more details : 
  - HDT and Hearthstone are both running with the same user
  - I got the following error in my HDT log : 
```
8:10:13 AM|Error|LoadingScreenHandler.CheckMirrorStatus >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at HearthMirror.ProcessView..ctor(Process proc)
   at HearthMirror.Mirror.get_View()
   at HearthMirror.Status.GetStatus()
```
It seems to be permissions-related too. Did you ever encounter this error and have you a fix for this ?

Thanks !

**Comment by xv1m** [comment]
For me adding exceptions for hdt and hearthstone in firewall solved problems.

**Comment by riQQ** [comment]
Which Firewall are you using?

**Comment by xv1m** [comment]
ZoneAlarm. Started to happen few days ago, i was getting this issue in hdt log "System.ComponentModel.Win32Exception (0x80004005): Access is denied",i uninstalled all bnet, hs and hdt deleted all remaining folders and files, did clean installs, didn't help. Dunno what happened what caused issue.

**Comment by KrakenHugo** [comment]
Are there any news regarding this topic? Still having the issue and am really hating all the other deck trackers I've been using in the meantime. Anything one can do to help?

**Comment by Demonsuji** [comment]
I decided to redownload HDT and try again recently after having this problem a while back.  It worked fine for a few days then went back to messing up like old times no matter what I tried doing.  If HDT starts working properly again, I would love to stick with it because there’s really nothing comparable out there that I can find.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by riQQ** [comment]
Has anyone tried if disabling UAC helps?

**Comment by Stylised** [comment]
Disabling UAC and windows defender does nothing to help the issue.

**Comment by quack1** [comment]
Furthermore, disabling a security feature should never be a solution

**Comment by riQQ** [comment]
You're completely right. I just wanted to know if it changes something.

**Comment by riQQ** [comment]
Could someone with this issue do the following. 

1. Download [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx). 
2. Right-click on the columns of the processes table, `Select columns...` and in the tab `Process Image` enable the checkbox `Integrity Level`. 
3. Which Integrity Levels does Process Explorer display for Hearthstone and HDT?

**Comment by Stylised** [comment]
Medium for both.

**Comment by Stylised** [comment]
People who are experiencing this issue: Are you using flux or some other screen colour altering software?

**Comment by sephyrix** [comment]
Yes I am having this issue and use flux

**Comment by Stylised** [comment]
Try turning flux off and starting hs and deck tracker. That more or less fixes it for me.

**Comment by mhk13** [comment]
I've been having this issue for ages now.... I'm obligated to switch to deck mate although I like HDT better.
would you please solve this soon?

**Comment by azeier** [comment]
If I had any idea how, I would, sorry :/.

**Comment by mhk13** [comment]
is there anything I can do to help solve it ?

**Comment by azeier** [comment]
It sometimes working is interesting. See if it's somehow related to the order of starting HDT and the Battle.net client/Hearthstone, or some other software running/not running when you start either.

**Comment by riQQ** [comment]
Someone using ZoneAlarm had the same problem and got it to work by changing settings: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2738#issuecomment-273560497

> For me adding exceptions for hdt and hearthstone in firewall solved problems.

**Comment by mhk13** [comment]
@azeier 
I thought so and I tried to test it a while back
I got best chances to get it working if I start battle net then HDT then HS, but that doesn;t work all the time

@riQQ He says he tried clean install every thing and it didn't work

**Comment by mhk13** [comment]
@azeier I think there might be some conflict with zonealarm
If I restart zonealarm (Exit and reopen) , there is a very high chance that HDT works normally
This might be a good starting point to check, I might consider switching away from zonealarm to private firewall or windows firewall control ... but now at this time frame 
Hope this helps

**Comment by riQQ** [comment]
@mhk13 yes, but adding exceptions for **both** HDT and Hearthstone worked for him, after a clean install didn't help.

**Comment by jackjoyce8** [comment]
I'm having this issue aswell, ran everything as admin and the issue still reproduces. Sometimes will work if i just keep restarting HDT over and over but it's hardly a solution. See hdt_log below:

[hdt_log_1495618319.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1025078/hdt_log_1495618319.txt)

**Comment by kissoff** [comment]
Same issue here. Following.

**Comment by riQQ** [comment]
Could someone try the following test program, that tries to open the Hearthstone process with a reduced set of access rights:
- Download `ReadProcessMemory.zip` from https://github.com/riQQ/ReadProcessMemory/releases/tag/v1
- extract it to a folder
- run Hearthstone
- run `ReadProcessMemory.exe` and post a screenshot of the console window.

**Comment by azeier** [comment]
I just randomly had this issue too for a while, starting Hearthstone via the button in HDT seemed to work for me.

**Comment by Kroweer574** [comment]
I just set HDT to open as admin and restarted PC and now it works fine.
Needed the restart tho.

**Comment by Jaroslove17** [comment]
Had this annoying problem,tried many things,didnt help at all. Adding these folders into firewall exception list solved the problem for me. I have Avast antivirus. Those folders are in C:/users/username/AppData/Local/ 
![image](https://user-images.githubusercontent.com/40152789/41207543-a845711a-6d20-11e8-8876-d05298013f78.png)
I suppose antivirus senses unexisting danger from Decktracker interacting with Hearthstone,like adware viruses infect browsers.

**Comment by Jaroslove17** [comment]
Fuck you,why delete my previous comment wtf

**Comment by riQQ** [comment]
Here's a test release that might fix this issues for some of you: https://github.com/HearthSim/HDT-dev-builds/releases/download/v1.7.2-dev3668/HDT-Installer.exe

This version will overwrite your current installation (keeps settings, stats etc) and automatically update to the next stable release once available.

Let me know if you notice any issues.

**Comment by riQQ** [comment]
Is anyone still having this issue?

**Comment by Nurgz** [comment]
I have this issue as of the most recent patch. nothing I try fixes it. I've tried re-installing both and I've tried running in admin. HDT works, but it won't sync with my game so my data hasn't uploaded since before the new patch. 

I have no idea how to fix it, but I hope someone can help as inn keeper doesn't work any more neither so I have no options now.

**Comment by Nurgz** [comment]
starting to get annoyed now. I've been trying to get help with this issue for 3 days now. I have tried everything and it doesn't work. 

is it an issue with the new HS patch or something as I just don't get it. no matter what I try I get the un even thing and I've tried doing what it says and it doesn't work. I've tried re-installing both HS and HDT multiple times and it doesn't work.

surely someone must know how to fix this?

**Comment by Nurgz** [comment]
is there an older version I can get or something? I really need some possible fixes beyond the two mentioned above as they don't work.

**Comment by Nurgz** [comment]
hey guys. sorry for all the comments. just letting you know that my issue was also with avast. I actually had 2 anti virus software packages running simultaneously. after removing avast, decktracker updated right away. 

If anyone runs into this issue, it might be your firewall or something.

**Comment by battlezones** [comment]
After years of running this brilliant app with no issues, all of a sudden I am getting the Uneven permissions problem as of this week, with nothing apparently changing.

Have tried all things suggested, including re-installing Hearthstone and HDT multiple times, running both as admin, resetting the log files, checking log locations. I have checked both Hearthstone and HDT are firewall enabled on Windows Defender.

The only thing I can think that has changed is that Windows Defender recently wanted me to enable Tamper Protection, which I did. But have since disabled Windows Defender as a test to see if that's the issue, but the Uneven permissions problem with HDT still persists.

If I run HDT as admin, then the message doesn't appear, but deck tracking etc doesn't work.

The strange thing is that probably 1 in 20 times it works as intended, but I can't seem to replicate the  conditions, and it seems fairly random when it does occasionally work.

I have dropped 2 log files, the first one is from when I did get a session working. The second one where the issue occurs, was just after when I closed Hearthstone and re-opened it. This was just a few minutes after the successful session...

I would love a solution to this, as it's very frustrating. The only thing I can think of for me is a PC reset, but it seems drastic when HDT clearly can work, and has been working well for ages.

[hdt_log_1564446835.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/3448516/hdt_log_1564446835.txt)
[hdt_log_1564447000.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/3448517/hdt_log_1564447000.txt)

**Comment by riQQ** [comment]
@battlezones the logs for the good and bad case look as expected.

Can you post a log of the following scenariao you mentioned:
> If I run HDT as admin, then the message doesn't appear, but deck tracking etc doesn't work.

**Comment by battlezones** [comment]
> @battlezones the logs for the good and bad case look as expected.
> 
> Can you post a log of the following scenariao you mentioned:
> 
> > If I run HDT as admin, then the message doesn't appear, but deck tracking etc doesn't work.

Log when running as administrator.

[hdt_log_1564612061.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/3454143/hdt_log_1564612061.txt)

**Comment by Nurgz** [comment]
this was a while back. I will run game tomorrow and see if any issues are persisting though.  I've not played in a little while.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by battlezones** [comment]
Only solution for me ended up to do a partial factory reset (PC needed a tidy up anyway so wasn't that disruptive), HDT back to working correctly again.

**Comment by riQQ** [comment]
Excerpt from battlezones' log:
```
11:23:42 PM|Warning|Core.Initialize >> HearthMirror Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at HearthMirror.ProcessView.GetExport(String name) in C:\projects\hearthstone-deck-tracker\HearthMirror\HearthMirror\ProcessView.cs:line 167
   at HearthMirror.Mirror.get_Root() in C:\projects\hearthstone-deck-tracker\HearthMirror\HearthMirror\Mirror.cs:line 46
   at HearthMirror.Reflection.GetAccountIdInternal() in C:\projects\hearthstone-deck-tracker\HearthMirror\HearthMirror\Reflection.cs:line 642
   at HearthMirror.Reflection.TryGetInternal[T](Func`1 action, Boolean clearCache) in C:\projects\hearthstone-deck-tracker\HearthMirror\HearthMirror\Reflection.cs:line 35
```
