### ISSUE TITLE
the deck builder still not work properly with some UI languages 

### ISSUE THREAD

**Issue by dyx00001** [HearthSim/Hearthstone-Deck-Tracker#2875]
using Chinese
System.Windows.Markup.XamlParseException: 设置 connectionId 时引发了异常。 ---> System.IO.FileNotFoundException: 未能加载文件或程序集“De.TorstenMandelkow.MetroChart, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d5b8d1bbc99c4a2a”或它的某一个依赖项。系统找不到指定的文件。
   在 Hearthstone_Deck_Tracker.Controls.Stats.Arena.Charts.ChartWinsByClass.System.Windows.Markup.IComponentConnector.Connect(Int32 connectionId, Object target)
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetConnectionId(Object root, Int32 connectionId, Object instance)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   在 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   在 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   在 System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   在 Hearthstone_Deck_Tracker.Controls.Stats.Arena.ArenaAdvancedCharts.InitializeComponent()
   在 Hearthstone_Deck_Tracker.Controls.Stats.Overview..ctor()
   在 Hearthstone_Deck_Tracker.Core.get_StatsOverview()
   在 Hearthstone_Deck_Tracker.DeckList.set_ActiveDeck(Deck value)
   在 Hearthstone_Deck_Tracker.Windows.MainWindow.SelectDeck(Deck deck, Boolean setActive)
   在 Hearthstone_Deck_Tracker.Windows.MainWindow.SetNewDeck(Deck deck, Boolean editing)
   在 Hearthstone_Deck_Tracker.Controls.DeckPicker.DeckPicker.BtnEditDeck_Click(Object sender, RoutedEventArgs e)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
@azeier 

using English
System.Windows.Markup.XamlParseException: Set connectionId threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'De.TorstenMandelkow.MetroChart, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d5b8d1bbc99c4a2a' or one of its dependencies. The System Cannot Find the File Specified.
   at Hearthstone_Deck_Tracker.Controls.Stats.Arena.Charts.ChartWinsByClass.System.Windows.Markup.IComponentConnector.Connect(Int32 connectionId, Object target)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetConnectionId(Object root, Int32 connectionId, Object instance)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Hearthstone_Deck_Tracker.Controls.Stats.Arena.ArenaAdvancedCharts.InitializeComponent()
   at Hearthstone_Deck_Tracker.Controls.Stats.Overview..ctor()
   at Hearthstone_Deck_Tracker.Core.get_StatsOverview()
   at Hearthstone_Deck_Tracker.DeckList.set_ActiveDeck(Deck value)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.<UseDeck>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by dyx00001** [comment]
@azeier update Microsoft .NET Framework 4.6.2 then all problem clear !
