### ISSUE TITLE
Metro.Controls.Dialogs.ProgressDialog no "progressdialog.xaml"

### ISSUE THREAD

**Issue by judge2020** [HearthSim/Hearthstone-Deck-Tracker#2919]
Stacktrace: 

```
System.Exception: The component 'MahApps.Metro.Controls.Dialogs.ProgressDialog' does not have a resource identified by the URI '/MahApps.Metro;component/themes/dialogs/progressdialog.xaml'.
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at MahApps.Metro.Controls.Dialogs.ProgressDialog.InitializeComponent()
   at MahApps.Metro.Controls.Dialogs.ProgressDialog..ctor(MetroWindow parentWindow, MetroDialogSettings settings)
   at MahApps.Metro.Controls.Dialogs.DialogManager.<>c__DisplayClass43.<ShowProgressAsync>b__3b()
   at System.Windows.Threading.DispatcherOperation`1.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback)
   at MahApps.Metro.Controls.Dialogs.DialogManager.<>c__DisplayClass43.<ShowProgressAsync>b__3a(Task z)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.<ImportDeckFromUrl>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.<ImportDeck>d__145.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

Not sure what the cause of this is, I've uninstalled and deleted the entire folder, then reinstalled and still happens. 

Class explorer in dotpeek shows that there is a Metro.Controls.Dialogs.ProgressDialog - 
https://www.youtube.com/watch?v=OpGeaYSgAfY

**Comment by riQQ** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2141#issuecomment-189381507.

**Comment by judge2020** [comment]
Ah alright, thanks. Was because I was using metro too in my plugin.
