### ISSUE TITLE
Unhandled exception: Hearthstone Deck Tracker Updater

### ISSUE THREAD

**Issue by deafen** [HearthSim/Hearthstone-Deck-Tracker#2949]
When I download the latest version via Hearthstone Deck Tracker Updater an unhandled exception is thrown. Here's a the stack trace:

Creating temp file directory
Downloading latest version... 26508/26508KB (100%)
Extracting files...

System.AggregateException: One or more errors occurred. ---> System.Exception: E
rror extracting the downloaded file. ---> System.IO.IOException: The file 'HDTUp
date_new.exe' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Bo
olean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at HDTUpdate.Program.CopyFiles(String dir, String newPath)
   at HDTUpdate.Program.<Update>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at HDTUpdate.Program.<Update>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at HDTUpdate.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Error extracting the downloaded file
. ---> System.IO.IOException: The file 'HDTUpdate_new.exe' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Bo
olean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at HDTUpdate.Program.CopyFiles(String dir, String newPath)
   at HDTUpdate.Program.<Update>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at HDTUpdate.Program.<Update>d__2.MoveNext()<---

There was an error installing the latest update. Press any key to open the websi
te for manual download.

**Comment by judge2020** [comment]
> The file 'HDTUp
date_new.exe' already exists.

Looks like an issue with squirrel, as it handles updates. However this error is weird, as it should just overwrite the update.

For now you can just install by going to https://hsdecktracker.net/download/

**Comment by riQQ** [comment]
This is not a squirrel issue.
See #2873.
