### ISSUE TITLE
HDT random crashes with OutOfMemoryException

### ISSUE THREAD

**Issue by Radiohawk58** [HearthSim/Hearthstone-Deck-Tracker#3054]
HDT suffers random "application has failed" and windows (Win10) closes it.

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/678216/hdt_log.txt)

**Comment by Radiohawk58** [comment]
Just crashed again - here's the new log file:
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/678237/hdt_log.txt)

**Comment by Radiohawk58** [comment]
another crash, not sure what I'm doing different than others - here's the latest log:
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/678282/hdt_log.txt)

**Comment by judge2020** [comment]
There are no error details in these logs. Whatever is causing the crash isn't being picked up by HDT's error handler.

**Comment by Radiohawk58** [comment]
Sry, don't mean to be spammy, just wanted to portray the frequency of crashes all of a sudden.  I tried a total shutdown of system then restart, then had Kaspersky do  full scan and root scan - went to bed while that happened.  Will update today if it continues.

By the way, thanks for all the hard work on software, is appreciated.

**Comment by Radiohawk58** [comment]
Here's the latest win event log details regarding HDT:

Application: Hearthstone Deck Tracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at Hearthstone_Deck_Tracker.LogReader.LogReader.ReadLogFile()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by azeier** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2991#issuecomment-264653751
> Yeah that out of memory crash is a known issue I still don't know how to fix (or why it happens) :(

**Comment by tknights2015** [comment]
Yesterday, was seeing multiple crashes in no deck mode, in Tavern Brawl.

**Comment by goldenmane** [comment]
cannot use the program anymore, everytime i open it the memory usage just rises and rises up to 1,5gb and then it just crashes.

**Comment by azeier** [comment]
Does that persist through restarting hearthstone / rebooting?

**Comment by goldenmane** [comment]
no, actually it stopped when i restarted both HS and Deck Tracker, seems like something was bugged, but its working fine now, memory doesnt exceed 150Mb

**Comment by ViezeVingertjes** [comment]
It has a huge memory leak, this might be the cause of your crashes. (Over 2GB RAM at times)

**Comment by azeier** [comment]
Definitely is, it's a know issue. We don't really know what's causing it though - likely related to the log reading somehow.
I haven't been able to reproduce it so far, which makes fixing it difficult :/.

**Comment by beheh** [comment]
More logs in #3104.

**Comment by beheh** [comment]
We should be pretty good on memory usage nowadays.
