### ISSUE TITLE
Deck Tracker keeps crashing on startup

### ISSUE THREAD

**Issue by listl89** [HearthSim/Hearthstone-Deck-Tracker#3078]
I'm trying to get Hearthstone Decktracker working, but it just keeps crashing on startup.
I currently have framework 4.5 installed (as it crashes on 4.6 also).

I have excluded it from microsoft security essentials. (both roaming and appdata folders)
I open the exe with administrator rights.
I have re-installed it several times.
I have tried deleting the config.xml

The only log that I can find in appdata/roaming says:

1:47:34 PM|Info|Core.Initialize >> HDT: 1.1.6.0, Operating System: Windows 7 Ultimate 7601, .NET Framework: 378389
1:47:34 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
1:47:36 PM|Info|ConfigManager.ConvertLegacyConfig >> changed config values
1:47:36 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
1:47:36 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
1:47:36 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
1:47:36 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
1:47:36 PM|Info|GameV2.Reset >> -------- Reset ---------
1:47:36 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets

Eventvwr Log says:

Application: Hearthstone Deck Tracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException
Stack:
   at System.Windows.Automation.Peers.AutomationPeer.ListenerExists(System.Windows.Automation.Peers.AutomationEvents)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Hearthstone_Deck_Tracker.App.Main()

Also the crash screen says this:
Error: The type initializer for 'System.Windows.Automation.Peers.AutomationPeer'... 
If I try to click 'Show Stacktrace' or anything else for that matter, it work stop working/crash.

Perhaps someone can help me.

**Comment by TemporalOnline** [comment]
All games? Mine keeps crashing when a brawl starts, if I start HDT while IN a brawl, it goes well, but as soon as I start another one, crash.

**Comment by riQQ** [comment]
@TemporalOnline your issue is different and should be fixed with the current version (1.1.6).

**Comment by listl89** [comment]
Fixed the problem follow @riQQ 's instructions from this thread: #2201
