### ISSUE TITLE
ERROR MESSAGE WHEN OPEN STATS

### ISSUE THREAD

**Issue by Evuam** [HearthSim/Hearthstone-Deck-Tracker#3090]
Hi all, i have an error message every time i open the stats and HDT crashs.
All the other functions works fine ( replay etc... ) The error message is:

**ERROR: set connectioId threw an exception**

This is the Stacktrace:

System.Windows.Markup.XamlParseException: Set connectionId threw an exception. ---> System.InvalidCastException: [A]MahApps.Metro.Controls.Flyout cannot be cast to [B]MahApps.Metro.Controls.Flyout. Type A originates from 'MahApps.Metro, Version=1.1.2.0, Culture=neutral, PublicKeyToken=f4fb5a3c4d1e5b4f' in the context 'LoadFrom' at location 'C:\Users\Fabrizio\AppData\Local\HearthstoneDeckTracker\app-1.1.6\Plugins\Hearthstone Deck Tracker\MahApps.Metro.dll'. Type B originates from 'MahApps.Metro, Version=1.1.2.0, Culture=neutral, PublicKeyToken=f4fb5a3c4d1e5b4f' in the context 'Default' at location 'C:\Users\Fabrizio\AppData\Local\HearthstoneDeckTracker\app-1.1.6\MahApps.Metro.dll'.
   at Hearthstone_Deck_Tracker.Windows.StatsWindow.System.Windows.Markup.IComponentConnector.Connect(Int32 connectionId, Object target)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetConnectionId(Object root, Int32 connectionId, Object instance)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Hearthstone_Deck_Tracker.Windows.StatsWindow.InitializeComponent()
   at Hearthstone_Deck_Tracker.Windows.StatsWindow..ctor()
   at Hearthstone_Deck_Tracker.Core.Windows.get_StatsWindow()
   at Hearthstone_Deck_Tracker.Windows.MainWindow.ShowStats(Boolean arena, Boolean matches)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.BtnConstructedStats_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

Someone can help me?

**Comment by riQQ** [comment]
Go to `%APPDATA%\HearthstoneDeckTracker\Plugins` and delete the folder `Hearthstone Deck Tracker`.

**Comment by Evuam** [comment]
ok, i did it. Now i have:

System.Windows.Markup.XamlParseException: Set connectionId threw an exception. ---> System.InvalidCastException: [A]MahApps.Metro.Controls.Flyout cannot be cast to [B]MahApps.Metro.Controls.Flyout. Type A originates from 'MahApps.Metro, Version=1.1.2.0, Culture=neutral, PublicKeyToken=f4fb5a3c4d1e5b4f' in the context 'LoadFrom' at location 'C:\Users\Fabrizio\Hearthstone.Deck.Tracker-v1.1.6\Hearthstone Deck Tracker\Plugins\Hearthstone Deck Tracker\MahApps.Metro.dll'. Type B originates from 'MahApps.Metro, Version=1.1.2.0, Culture=neutral, PublicKeyToken=f4fb5a3c4d1e5b4f' in the context 'Default' at location 'C:\Users\Fabrizio\Hearthstone.Deck.Tracker-v1.1.6\Hearthstone Deck Tracker\MahApps.Metro.dll'.
   at Hearthstone_Deck_Tracker.Windows.StatsWindow.System.Windows.Markup.IComponentConnector.Connect(Int32 connectionId, Object target)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetConnectionId(Object root, Int32 connectionId, Object instance)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Hearthstone_Deck_Tracker.Windows.StatsWindow.InitializeComponent()
   at Hearthstone_Deck_Tracker.Windows.StatsWindow..ctor()
   at Hearthstone_Deck_Tracker.Core.Windows.get_StatsWindow()
   at Hearthstone_Deck_Tracker.Windows.MainWindow.ShowStats(Boolean arena, Boolean matches)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.BtnConstructedStats_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Evuam** [comment]
i think that the folder in /pluggins will create automatically when HDT starts to run...
I closed HDT
I Deleted the folder in /pluggins
I run HDT
After this i checked if the folder was empty and then there were a new folder "Hearthstone Deck Tracker"

**Comment by riQQ** [comment]
You deleted the wrong folder. You have to delete this one: C:\Users\Fabrizio\AppData\\**Roaming**\HearthstoneDeckTracker\Plugins\.

**Comment by Evuam** [comment]
Ok, thank you. It works 
Bye 


Inviato da iPhone

**Comment by beheh** [comment]
Appears fixed.
