### ISSUE TITLE
Getting HSDT not running same permisions

### ISSUE THREAD

**Issue by falconmick** [HearthSim/Hearthstone-Deck-Tracker#3174]
Hey guys,
Since about yesterday my HSDT no longer works, I start a game and it just sits there with my deck and doesn't update to cards drawn. Sometimes (not always) I see a error message regarding that HSDT is not running under the same account as Hearthstone, however I have launched neither as Admin and when I check their process details both are running under the same account (see below)

I've checked log files and there are no errors other than an in-ability to connect to  52.2.0.123:8086 as also seen below

What can I do to debug?

```
12:52:52 PM|Info|GameV2.CurrentMode >> TOURNAMENT
12:52:53 PM|Info|ApiWrapper.UpdateAccountStatus >> Id=0, Username=, Status=Anonymous
12:52:53 PM|Debug|Influx.WritePoint >> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 52.2.0.123:8086
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.Utility.Analytics.Influx.<WritePoint>d__6.MoveNext()
12:52:54 PM|Info|FullScreenFxHandler.Handle >> Now in queue (4/9/2017 12:52:54 PM)
12:52:54 PM|Info|FullScreenFxHandler.AutoSelectDeckById >> No selected deck found, using no-deck mode
12:52:54 PM|Info|DeckList.ActiveDeck >> Set active deck to: 
12:52:54 PM|Debug|XmlManager.Save >> Saving file: C:\Users\xxx\AppData\Roaming\HearthstoneDeckTracker\config.xml
12:52:54 PM|Debug|XmlManager.Save >> File saved: C:\Users\xxx\AppData\Roaming\HearthstoneDeckTracker\config.xml
12:52:55 PM|Debug|XmlManager.Load >> Loading file: C:\Users\xxx\AppData\Roaming\HearthstoneDeckTracker\DefaultDeckStats.xml
12:52:55 PM|Debug|XmlManager.Load >> File loaded: C:\Users\xxx\AppData\Roaming\HearthstoneDeckTracker\DefaultDeckStats.xml
12:52:55 PM|Info|GameV2.Reset >> -------- Reset ---------
12:52:55 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
12:52:56 PM|Info|LogWatcherManager.OnLogFileFound >> Power
12:52:56 PM|Info|LogWatcherManager.OnLogFileFound >> Rachelle
```

![image](https://cloud.githubusercontent.com/assets/713449/24833660/6a3b053a-1d24-11e7-8c89-aa167f2f4b2d.png)

**Comment by Werwolfsoul** [comment]
the same problem since today/maybe yesterday
win7 64
![image](https://cloud.githubusercontent.com/assets/19953370/24836365/be9ace28-1d22-11e7-9f5b-546cd7b46a70.png)

**Comment by falconmick** [comment]
Windows 10 64bit
