### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by instinctual07** [HearthSim/Hearthstone-Deck-Tracker#3234]
Greetings,

I installed HDT a few days ago and it has been working great until today. It crashed earlier and now when I try and run the program it crashes on start up. I've followed the steps from multiple other threads regarding crash on start up issues (ie NET framework, uninstall/reinstall, delete folder in Roaming AppData) and still no dice. Any help would be greatly appreciated.

Love the program, thanks guys.

11:00:12 PM|Info|Core.Initialize >> HDT: 1.2.5.3045, Operating System: Windows 10 Pro 14393, .NET Framework: 394802
11:00:37 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
11:00:40 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
11:00:40 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
11:00:40 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
11:00:40 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
11:00:40 PM|Info|GameV2.Reset >> -------- Reset ---------
11:00:40 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
11:00:42 PM|Info|HsReplayDecks.LoadFromDisk >> Loading data from disk...
11:00:42 PM|Info|HsReplayDecks.Load >> Loaded from disk: 
11:00:42 PM|Info|HsReplayDecks.Load >> Cached data was not found or stale. Fetching latest...
11:00:42 PM|Info|ApiWrapper.GetAvailableDecks >> Fetching available decks...
11:00:42 PM|Info|ApiWrapper.GetUploadToken >> Requesting new upload token...
11:00:42 PM|Info|OverlayWindow.SetTopmost >> Hearthstone window not found
11:00:43 PM|Info|GameV2.Reset >> -------- Reset ---------
11:00:43 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
11:00:44 PM|Info|BackupManager.Run >> Running BackupManager
11:00:44 PM|Info|BackupManager.Run >> Backup for today already exists
11:00:44 PM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
11:00:44 PM|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: Checking for updates (current=1.2.5.3045, pre-release=False)

The program Hearthstone Deck Tracker.exe version 1.2.5.3045 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 3574
 Start Time: 01d2c4589b636a7d
 Termination Time: 4
 Application Path: C:\Program Files (x86)\Hearthstone.Deck.Tracker-v1.2.5\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe
 Report Id: fa3765da-304b-11e7-b4d8-9c5c8e76b773
 Faulting package full name: 
 Faulting package-relative application ID:

**Comment by riQQ** [comment]
Please provide crash logs. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues (sections `HDT crash logs` and `Windows log files`). There has to be either one.

**Comment by instinctual07** [comment]
HDT Log:

11:28:54 PM|Info|Core.Initialize >> HDT: 1.2.5.3045, Operating System: Windows 10 Pro 14393, .NET Framework: 394802
11:28:55 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
11:28:56 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
11:28:56 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
11:28:56 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
11:28:56 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
11:28:56 PM|Info|GameV2.Reset >> -------- Reset ---------
11:28:56 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
11:28:57 PM|Info|HsReplayDecks.LoadFromDisk >> Loading data from disk...
11:28:57 PM|Info|HsReplayDecks.Load >> Loaded from disk: 
11:28:57 PM|Info|HsReplayDecks.Load >> Cached data was not found or stale. Fetching latest...
11:28:57 PM|Info|ApiWrapper.GetAvailableDecks >> Fetching available decks...
11:28:57 PM|Info|ApiWrapper.GetUploadToken >> Requesting new upload token...
11:28:57 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
11:28:57 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
11:28:58 PM|Info|GameV2.Reset >> -------- Reset ---------
11:28:58 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
11:28:59 PM|Info|BackupManager.Run >> Running BackupManager
11:28:59 PM|Info|BackupManager.Run >> Backup for today already exists
11:28:59 PM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
11:28:59 PM|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: Checking for updates (current=1.2.5.3045, pre-release=False)
11:28:59 PM|Info|Helper.GetCurrentRegion >> Region: US
11:28:59 PM|Info|BackupManager.Run >> Running BackupManager
11:28:59 PM|Info|BackupManager.Run >> Backup for today already exists
11:28:59 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.


Faulting application name: Hearthstone Deck Tracker.exe, version: 1.2.5.3045, time stamp: 0x5908a907
Faulting module name: KERNELBASE.dll, version: 10.0.14393.1066, time stamp: 0x58d9f07f
Exception code: 0xe0434352
Fault offset: 0x000da932
Faulting process id: 0x375c
Faulting application start time: 0x01d2c44e7f9b804f
Faulting application path: C:\Program Files (x86)\Hearthstone.Deck.Tracker-v1.2.5\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 7c619910-6945-4aea-94f1-d0ce808968be
Faulting package full name: 
Faulting package-relative application ID: 

Windows Logs:

Application: Hearthstone Deck Tracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare)
   at MS.Internal.AppModel.SiteOfOriginPart.HandleFileSource(Boolean)
   at MS.Internal.AppModel.SiteOfOriginPart.GetStreamAndSetContentType(Boolean)
   at MS.Internal.AppModel.SiteOfOriginPart.GetStreamCore(System.IO.FileMode, System.IO.FileAccess)
   at System.IO.Packaging.PackagePart.GetStream(System.IO.FileMode, System.IO.FileAccess)
   at System.IO.Packaging.PackWebResponse+CachedResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.get_ContentType()
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCacheOption, System.Guid ByRef, Boolean ByRef, System.IO.Stream ByRef, System.IO.UnmanagedMemoryStream ByRef, Microsoft.Win32.SafeHandles.SafeFileHandle ByRef)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(System.Uri, System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Net.Cache.RequestCachePolicy, Boolean)
   at System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(System.Uri, System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Net.Cache.RequestCachePolicy)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext, System.Globalization.CultureInfo, System.Object)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateObjectWithTypeConverter(MS.Internal.Xaml.ServiceProviderContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateFromValue(MS.Internal.Xaml.ServiceProviderContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object, System.Xaml.XamlMember)
   at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.CreateFromValue(MS.Internal.Xaml.ServiceProviderContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object, System.Xaml.XamlMember)
   at System.Xaml.XamlObjectWriter.Logic_CreateFromValue(MS.Internal.Xaml.Context.ObjectWriterContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object, System.Xaml.XamlMember, System.String, MS.Internal.Xaml.Runtime.IAddLineInfo)

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadComponent(System.Object, System.Uri)
   at Hearthstone_Deck_Tracker.App.InitializeComponent()
   at Hearthstone_Deck_Tracker.App.Main()

**Comment by instinctual07** [comment]
I have no idea why but it's working again. Thanks!
