### ISSUE TITLE
PowerHandler Null Reference Exception

### ISSUE THREAD

**Issue by riQQ** [HearthSim/Hearthstone-Deck-Tracker#3260]
I'm using the dev build.
Logs are here: https://gist.github.com/riQQ/3ec5cc4dc25b801f67154b81a6f2f7b6
The crash happened after importing a deck from metastats.

Stacktrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.LogReader.Handlers.PowerHandler.Handle(String logLine, IHsGameState gameState, IGame game)
   at Hearthstone_Deck_Tracker.LogReader.LogWatcherManager.OnNewLines(List`1 lines)
   at HearthWatcher.LogWatcher.<Start>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by riQQ** [comment]
I was able to debug it:
In this line, `CurrentBlock` is null: https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/e4e372f9a8a8d08ab6a3e006142939b9f3c49c92/Hearthstone%20Deck%20Tracker/LogReader/Handlers/PowerHandler.cs#L329
