### ISSUE TITLE
HDT 1.3.2 crashes when starting a constructed game

### ISSUE THREAD

**Issue by aalear** [HearthSim/Hearthstone-Deck-Tracker#3267]
### Expected Behavior
No crash :)

### Actual Behavior
HDT crashes with a null ref (stack trace below) when I click "Play Standard" from the deck selection screen.

### Steps to reproduce behavior
- Enter deck selection
- Click the button to initiate opponent search

### Stack Trace

```
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Hearthstone_Deck_Tracker.Importing.DeckImporter.GetConstructedDecks()
   at Hearthstone_Deck_Tracker.Importing.DeckImporter.get_ConstructedDecksCache()
   at Hearthstone_Deck_Tracker.LogReader.Handlers.FullScreenFxHandler.AutoSelectDeckById(Mode mode)
   at Hearthstone_Deck_Tracker.LogReader.Handlers.FullScreenFxHandler.Handle(LogLine logLine, IGame game)
   at Hearthstone_Deck_Tracker.LogReader.LogWatcherManager.OnNewLines(List`1 lines)
   at HearthWatcher.LogWatcher.<Start>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by azeier** [comment]
Are you by any chance somehow still on Hearthstone 8.0.4?

**Comment by azeier** [comment]
This will sadly be a bit of a guessing game, because I don't seem to have any problems with it myself.

Unzip this [HearthMirror.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1046954/HearthMirror.zip) into `%LocalAppData%/HearthstoneDeckTracker/app-1.3.2` (or your HDT installation dir if you are using the zip version) and replace the existing HearthMirror.dll. See if that helps.

You can just paste that path into the windows run dialog (Win+R).

**Comment by aalear** [comment]
Hearthstone 8.2.0.19506 here now, and I can no longer repro the crash. I'm going to guess it updated sometime overnight here. ¯\_(ツ)_/¯

Thanks!
