### ISSUE TITLE
Decks will not import after fresh install of OS, etc.

### ISSUE THREAD

**Issue by kquade** [HearthSim/Hearthstone-Deck-Tracker#3318]
## Bug report
Decks will not import.

### Actual Behavior
HDT constantly says that there are no new decks to import.

### Steps to reproduce behavior
Reinstall Windows 10 Creator Edition.
Reinstall Hearthstone.
Reinstall HDT.

### Log/Screenshots
10:39:40 PM|Info|Core.Initialize >> HDT: 1.1.5.1, Operating System: Windows 10 Pro Insider Preview 16232, .NET Framework: 461275
10:39:41 PM|Info|Updater.StartupUpdateCheck >> Checking for updates
10:39:41 PM|Info|Updater.GetReleaseUrl >> Downloading releases file
10:39:41 PM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
10:39:43 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
10:39:43 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
10:39:43 PM|Info|Updater.SquirrelUpdate >> Downloading 9 delta releases, latest=1.3.5.0
10:39:49 PM|Error|Updater.SquirrelUpdate >> System.Net.WebException: The request was aborted: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.ConnectStream.ReadWithoutValidation(Byte[] buffer, Int32 offset, Int32 size, Boolean abortOnError)
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadFile>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Hearthstone_Deck_Tracker.Utility.Updating.Updater.<SquirrelUpdate>d__13.MoveNext()
10:39:49 PM|Warning|Updater.SquirrelUpdate >> Now using china mirror
10:39:49 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
10:39:49 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
10:39:49 PM|Info|Updater.SquirrelUpdate >> Downloading 9 delta releases, latest=1.3.5.0
10:39:53 PM|Info|SplashScreenWindow.StartSkipTimer >> Showing skip button
10:39:55 PM|Error|Updater.SquirrelUpdate >> System.Net.WebException: The request was aborted: The connection was closed unexpectedly.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.HttpWebRequest.MakeMemoryStream(Stream stream)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadFile>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Hearthstone_Deck_Tracker.Utility.Updating.Updater.<SquirrelUpdate>d__13.MoveNext()
10:39:55 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
10:39:55 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
10:39:55 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
10:39:55 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
10:39:55 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
10:39:55 PM|Info|GameV2.Reset >> -------- Reset ---------
10:39:55 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
10:39:56 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
10:39:57 PM|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.
10:39:57 PM|Info|GameV2.Reset >> -------- Reset ---------
10:39:57 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
10:39:57 PM|Info|BackupManager.Run >> Running BackupManager
10:39:57 PM|Info|BackupManager.Run >> Backup for today already exists
10:39:57 PM|Info|PluginManager.LoadPlugins >> Loading Plugins...
10:39:57 PM|Info|ApiWrapper.UpdateAccountStatus >> Checking account status...
10:39:57 PM|Info|ApiWrapper.UpdateAccountStatus >> Id=0, Username=, Status=Anonymous

**Comment by judge2020** [comment]
You are not on creators update.

> Operating System: Windows 10 Pro Insider Preview 16232, .NET Framework: 461275

Build 1703 is the widely released creators update, and I can't find a source for that .Net build number

**Comment by judge2020** [comment]
Based on your system info it looks like you are running some windows insider preview build. In order to reduce the amount of variables try unsubscribing from insider builds in Windows settings.

**Comment by kquade** [comment]
Sure am. I've been on the fast track since day 1. Since this reinstall however, I have slowed down the incoming updates.

**Comment by kquade** [comment]
Strangest thing ... I uninstalled and reinstalled HDT (for the Nth time) and now it suddenly works.
