### ISSUE TITLE
No decks, no play dected

### ISSUE THREAD

**Issue by floriankrog** [HearthSim/Hearthstone-Deck-Tracker#3354]
### Expected Behavior
see my deck and info while playing, see what oppent plays.

### Actual Behavior
No deck detected (enemy and mine), nothing works. Only the applications frame, like the counters (attack, spell,...) and such, are visible but empty.

### Steps to reproduce behavior
- Open HDT
- Launch Hearthstone through HDT-App
- enter "Play Menu" for deck auto-detection, but nothing
- When I go to Import in HDT, it says "no new decks found"
- when beginning to play, as said before, there seem to be no connection to Heartstone as the HDT-boxes are shown but empty

### Fixes already tried out
- set the hearthstone path manually in config.xml
- manually updated the log.config file from Hearthstone like in the FAQ
- re-installed Hearthstone and HDT
- repeated the above... but nothing
- Hearthstone log-files are up to date, nothing blocked by anti-virus or else

### Log/Screenshots
`10:12:04 PM|Info|FullScreenFxHandler.Handle >> Now in queue (8/7/2017 10:12:04 PM)
10:12:04 PM|Error|DeckImporter.FromConstructed >> System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Hearthstone_Deck_Tracker.Importing.DeckImporter.GetConstructedDecks()
   at Hearthstone_Deck_Tracker.Importing.DeckImporter.FromConstructed()
10:12:04 PM|Warning|FullScreenFxHandler.AutoSelectDeckById >> No deck with id=1282576929 found
10:12:10 PM|Info|GameEventHandler.HandleGameStart >> --- Game start ---
10:12:10 PM|Info|GameV2.Reset >> -------- Reset ---------
10:12:10 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
10:12:10 PM|Info|TurnTimer.Start >> Starting turn timer
10:12:10 PM|Warning|TurnTimer.Start >> Waiting for player entity
10:12:14 PM|Info|GameV2.CurrentMode >> GAMEPLAY
10:12:15 PM|Info|TagChangeActions.SetHeroAsync >> Found hero with id=64
10:12:15 PM|Info|TagChangeActions.SetHeroAsync >> Waiting for PlayerEntity to exist
10:12:15 PM|Info|TagChangeActions.SetHeroAsync >> Found hero with id=66
10:12:15 PM|Info|TagChangeActions.SetHeroAsync >> Waiting for PlayerEntity to exist
10:15:24 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
10:15:29 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=True)
10:15:34 PM|Warning|Database.GetCardFromId >> Could not find card with ID=UNG_928
10:19:24 PM|Info|PowerHandler.Handle >> Found known cardId for entity 82: CFM_324t
10:21:09 PM|Info|TurnTimer.Stop >> Stopping turn timer
10:21:09 PM|Info|GameEventHandler.HandleGameEnd >> Game ended...
10:21:09 PM|Info|GameEventHandler.HandleGameEnd >> Format: Standard
10:21:09 PM|Info|GameStats.GameEnd >> Current Game ended after 0 turns
10:21:09 PM|Error|GameEventHandler.HandleGameEnd >> Error saving to DefaultDeckStats: System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.GameEventHandler.<HandleGameEnd>d__46.MoveNext()
10:21:09 PM|Info|LogUploader.Upload >> Uploading -16514456...
10:21:09 PM|Info|LogUploader.TryUpload >> Creating upload request...
10:21:10 PM|Info|LogUploader.TryUpload >> Upload Id: 8kZ8UzMicsuSnaXUrRXvoc
10:21:11 PM|Info|LogUploader.TryUpload >> Upload complete
10:21:11 PM|Info|LogUploader.Upload >> -16514456 complete. Success=True
10:21:19 PM|Info|GameV2.CurrentMode >> TOURNAMENT
10:21:20 PM|Error|DeckImporter.FromConstructed >> System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Hearthstone_Deck_Tracker.Importing.DeckImporter.GetConstructedDecks()
   at Hearthstone_Deck_Tracker.Importing.DeckImporter.FromConstructed()
10:21:20 PM|Info|GameEventHandler.HandleInMenu >> Game is now in menu.
10:21:20 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
10:21:20 PM|Info|GameEventHandler.SaveAndUpdateStats >> Saving DefaultDeckStats
10:22:20 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status`

**Comment by floriankrog** [comment]
update to the latest version did the trick... sorry to bother haha
