### ISSUE TITLE
Deck Tracker keeps crashing, even when trying to reinstall....please help!

### ISSUE THREAD

**Issue by terence1981s** [HearthSim/Hearthstone-Deck-Tracker#3381]
Hi there, recently my pc recovered from a blue screen crash, and windows 10 (latest version with auto updates) repaired itself. After the recovery though, HS Deck tracker keeps crashing. Even after i tried uninstalling and reinstalling the latest version (which i was already using), I get the same crash/error message when trying to install (though had no problem with uninstalling). The message reads: 

Error: Set property 'System.Windows.Controls.TextBlock.Text' threw an exception.

I don't know what this means or how to solve it. I attach a screengrab here:

![hs dt crash](https://user-images.githubusercontent.com/31148959/29483004-5e77ee76-84cf-11e7-9d54-a2b7c0376f91.jpg)

As you can see, the splash image just hangs and nothing progresses further. Can someone please help me?

**Comment by riQQ** [comment]
Could you push show stack trace and post it here?

**Comment by azeier** [comment]
I think I found it in sentry:
```
XamlParseException: Set property 'System.Windows.Controls.TextBlock.Text' threw an exception.
  Module "System.Windows.Threading.ExceptionWrapper", line 2, col 0, in TryCatchWhen
    System.Object TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
  Module "System.Windows.Threading.ExceptionWrapper", line 142, col 0, in InternalRealCall
    System.Object InternalRealCall(System.Delegate, System.Object, Int32)
  Module "System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c", line 0, col 0, in <ThrowAsync>b__6_0
    Void <ThrowAsync>b__6_0(System.Object)
  Module "Hearthstone_Deck_Tracker.Core+<Initialize>d__42", line 380, col 0, in MoveNext
    Void MoveNext()
  Module "Hearthstone_Deck_Tracker.Windows.MainWindow", line 6, col 0, in .ctor
    Void .ctor()
  Module "Hearthstone_Deck_Tracker.Windows.MainWindow", line 28, col 0, in InitializeComponent
    Void InitializeComponent()
  Module "System.Windows.Application", line 341, col 0, in LoadComponent
    Void LoadComponent(System.Object, System.Uri)
  Module "System.Windows.Markup.XamlReader", line 239, col 0, in LoadBaml
    System.Object LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
  Module "System.Windows.Markup.WpfXamlLoader", line 20, col 0, in LoadBaml
    System.Object LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
  Module "System.Windows.Markup.WpfXamlLoader", line 246, col 0, in Load
    System.Object Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
BadImageFormatException: Could not load file or assembly 'PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The module was expected to contain an assembly manifest.
  Module "MS.Internal.Xaml.Runtime.ClrObjectRuntime", line 10, col 0, in SetValue
    Void SetValue(System.Object, System.Xaml.XamlMember, System.Object)
  Module "MS.Internal.Xaml.Runtime.ClrObjectRuntime", line 0, col 0, in SetValue
    Void SetValue(System.Xaml.XamlMember, System.Object, System.Object)
  Module "System.Windows.Baml2006.WpfKnownMemberInvoker", line 0, col 0, in SetValue
    Void SetValue(System.Object, System.Object)
  Module "System.Windows.DependencyObject", line 594, col 0, in SetValueCommon
    Void SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
  Module "System.Windows.Data.BindingExpressionBase", line 28, col 0, in OnAttach
    Void OnAttach(System.Windows.DependencyObject, System.Windows.DependencyProperty)
  Module "System.Windows.Data.BindingExpression", line 169, col 0, in AttachOverride
    Boolean AttachOverride(System.Windows.DependencyObject, System.Windows.DependencyProperty)
  Module "System.Windows.Data.BindingExpression", line 929, col 0, in AttachToContext
    Void AttachToContext(AttachAttempt)
  Module "System.Windows.Data.BindingExpression", line 204, col 0, in Activate
    Void Activate(System.Object)
  Module "MS.Internal.Data.ClrBindingWorker", line 8, col 0, in AttachDataItem
    Void AttachDataItem()
  Module "MS.Internal.Data.PropertyPathWorker", line 154, col 0, in UpdateSourceValueState
    Void UpdateSourceValueState(Int32, System.ComponentModel.ICollectionView, System.Object, Boolean)
  Module "MS.Internal.Data.PropertyPathWorker", line 1100, col 0, in ReplaceItem
    Void ReplaceItem(Int32, System.Object, System.Object)
  Module "MS.Internal.Data.DataBindEngine", line 13, col 0, in RegisterForCacheChanges
    Void RegisterForCacheChanges(System.Object, System.Object)
  Module "MS.Internal.Data.ValueTable", line 0, col 0, in ShouldCache
    Boolean ShouldCache(System.Object, System.ComponentModel.PropertyDescriptor)
  Module "MS.Internal.SystemDataHelper", line 0, col 0, in IsDataSetCollectionProperty
    Boolean IsDataSetCollectionProperty(System.ComponentModel.PropertyDescriptor)
  Module "MS.Internal.AssemblyHelper", line 18, col 0, in ExtensionsForSystemData
    MS.Internal.SystemDataExtensionMethods ExtensionsForSystemData(Boolean)
  Module "MS.Internal.AssemblyHelper", line 79, col 0, in LoadExtensionFor
    System.Object LoadExtensionFor(System.String)
  Module "System.Activator", line 2, col 0, in CreateInstance
    System.Runtime.Remoting.ObjectHandle CreateInstance(System.String, System.String)
  Module "System.Activator", line 60, col 0, in CreateInstance
    System.Runtime.Remoting.ObjectHandle CreateInstance(System.String, System.String, Boolean, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[], System.Security.Policy.Evidence, Sys...
  Module "System.Reflection.RuntimeAssembly", line 99, col 0, in InternalLoadAssemblyName
    System.Reflection.RuntimeAssembly InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
  Module "System.Reflection.RuntimeAssembly", line 0, col 0, in nLoad
    System.Reflection.RuntimeAssembly nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
  Module "System.Reflection.RuntimeAssembly", col 0, in _nLoad
```

That sounds like your .NET Framework is outdated/corrupt.
Try running the [repair tool](https://www.microsoft.com/en-us/download/details.aspx?id=30135) or reinstalling it if that doesn't help.

**Comment by terence1981s** [comment]
I'll try the repair tool. The stacktrace is below: 
System.Windows.Markup.XamlParseException: Set property 'System.Windows.Controls.TextBlock.Text' threw an exception. ---> System.BadImageFormatException: Could not load file or assembly 'PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The module was expected to contain an assembly manifest.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName)
   at MS.Internal.AssemblyHelper.LoadExtensionFor(String name)
   at MS.Internal.AssemblyHelper.ExtensionsForSystemData(Boolean force)
   at MS.Internal.SystemDataHelper.IsDataSetCollectionProperty(PropertyDescriptor pd)
   at MS.Internal.Data.ValueTable.ShouldCache(Object item, PropertyDescriptor pd)
   at MS.Internal.Data.DataBindEngine.RegisterForCacheChanges(Object item, Object descriptor)
   at MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.AttachDataItem()
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.AttachOverride(DependencyObject target, DependencyProperty dp)
   at System.Windows.Data.BindingExpressionBase.OnAttach(DependencyObject d, DependencyProperty dp)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.InitializeComponent()
   at Hearthstone_Deck_Tracker.Windows.MainWindow..ctor()
   at Hearthstone_Deck_Tracker.Core.<Initialize>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by terence1981s** [comment]
Thanks again. Waiting eagerly on your reply, you geniuses! :)

**Comment by terence1981s** [comment]
Alright, made sure I had the latest version of .NET framework. 4.7, since i am upgraded to the Windows 10 creators update. Its working fine. 
When I try to install the HS Decktracker, i get the same error and the 'Stacktrace' is as below:

System.Windows.Markup.XamlParseException: Set property 'System.Windows.Controls.TextBlock.Text' threw an exception. ---> System.BadImageFormatException: Could not load file or assembly 'PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The module was expected to contain an assembly manifest.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName)
   at MS.Internal.AssemblyHelper.LoadExtensionFor(String name)
   at MS.Internal.AssemblyHelper.ExtensionsForSystemData(Boolean force)
   at MS.Internal.SystemDataHelper.IsDataSetCollectionProperty(PropertyDescriptor pd)
   at MS.Internal.Data.ValueTable.ShouldCache(Object item, PropertyDescriptor pd)
   at MS.Internal.Data.DataBindEngine.RegisterForCacheChanges(Object item, Object descriptor)
   at MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.AttachDataItem()
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.AttachOverride(DependencyObject target, DependencyProperty dp)
   at System.Windows.Data.BindingExpressionBase.OnAttach(DependencyObject d, DependencyProperty dp)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.InitializeComponent()
   at Hearthstone_Deck_Tracker.Windows.MainWindow..ctor()
   at Hearthstone_Deck_Tracker.Core.<Initialize>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Would really appreciate your help. I am normally fairly good at troubleshooting but this is a bit beyond me... :(

**Comment by Zawodowiec1532** [comment]
Is your Windows 32 bit only?

**Comment by azeier** [comment]
Did you run the repair tool?

**Comment by terence1981s** [comment]
yes ran the repair tool, all good. its windows 10 with all latest updates and its 64 bit
can anyone make sense of the 'stacktrace'?

**Comment by azeier** [comment]
Well, the stack trace means there is most likely something wrong with your .net framework installation :/.

You could try running the non-installer version: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/tag/v1.4.0

**Comment by terence1981s** [comment]
I suppose there could be something corrupt within my .NET framework the fix tool didn't manage to correct. The non-installer version throws up the same error (held out hope there for a bit). I tried uninstalling the .NET framework 4.7 from control panel and reinstalling it but the installation says it won't install because a newer version is already installed on my machine (this is after uninstalling ver 4.7 and restarting my pc). Any way I can totally uninstall all components of the .NET framework on my pc and then reinstall?

**Comment by terence1981s** [comment]
I would appreciate any advice since I've grown so accustomed to playing HS with my decktracker, I don't feel like playing without it :(

**Comment by Bert-Proesmans** [comment]
Since you said it happened after a crash and you're running Creator's update; run DISM to fix broken components of Windows (.net 4.7 is part of these).
This only works if your Windows Update isn't broken:

1. Open an elevated command prompt
    1. Go to start
    2. Type cmd
    3. Right click the suggested program (command prompt [cmd.exe]) and choose `run as administrator`
2. execute `dism /Online /Cleanup-image /Restorehealth`, this uses Windows Update to fix corrupt component packages
3. execute `sfc /scannow`, this will fix corrupt component files 

Afterwards deck tracker might work again, if not run the .Net repair tool again.

**Comment by terence1981s** [comment]
Alright, I have done as instructed. Here are the results:

![clipboard01ww](https://user-images.githubusercontent.com/31148959/29504591-5178c7fe-8673-11e7-9d63-607481dfa7e6.jpg)

Here is the dism.log (txt):

[dism.log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1237840/dism.log.txt)

Here is the cbs.log (txt):

[CBS.log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1237843/CBS.log.txt)

Not sure about the 'source' option mentioned in the cmd dialog. I ugraded my win8.1 to win10 via the free upgrade microsoft provided to windows users, so I have a folder on c: called 'Windows10Upgrade', but thats about it.

As for the sfc /scannow results, this was actually the first thing I did after the crash and the results were the same as shown in the cmd dialog above (pic) - of course I don't pretend to understand the cbs.log.

Do you think I should reboot and use advanced recovery options to reboot into command prompt and try these two operations again? I don't see how that would solve the 'source' problem from the dism operation though.....

As always, your advice would be much appreciated, I am at the limits of my tech savvy-ness

**Comment by Zawodowiec1532** [comment]
First run this one:

1. `Dism.exe /online /Cleanup-Image /StartComponentCleanup`
2. `sfc /scannow`

To run RestoreHealth with Cleanup-Image you need mounted ISO of WIndows10. Previously you could easy download it from Microsoft TechBench, but they removed it. You need to create new one with Microsoft Media Tools. After you will get ISO and mount it to e.g F: drive. Run commands:

1. `Dism /Online /Cleanup-Image /RestoreHealth /Source:wim:F:\sources\install.wim:1 /limitaccess`
2. `sfc /scannow`

And to check overall health run:

1. `dism /online /cleanup-image /checkhealth`

**Comment by Bert-Proesmans** [comment]
From the logs i guess there is some kind of ownership issue with/within your Windows folder making it fail integrity tests. Strange to see that Windows itself seems to not care and doesn't try to explicitly fix this.

Performing a restore from a new installation medium is already grey zone where i would consider clean reinstalling windows entirely. Not that i recommend that in every situation but it's the option which has definite success.

**Comment by terence1981s** [comment]
At a raised command prompt, /StartComponentCleanup returns this error:
![clipboard01eee](https://user-images.githubusercontent.com/31148959/29547732-7fce635a-872e-11e7-9d2a-f2d5aa98ca29.jpg)

afterwhich sfc /scannow retuns the same error as before.

Used media tools to create the ISO as instructed, mounted to G: then executed the dism command with the drive changed to G: instead of F:
This returned the same error as before, as did the subsequent sfc /scannow operation

After these operations, dism checkhealth returned this:
![clipboard01cccccckkkkk](https://user-images.githubusercontent.com/31148959/29547856-52b9770a-872f-11e7-8a30-c8bc111d612e.jpg)
I even found these links and basically tried these approaches:
http://www.thewindowsclub.com/dism-fails-source-files-could-not-be-found

have not tried this one yet (it seems not to really fix anything that isn't already working):
http://www.thewindowsclub.com/repair-corrupt-windows-image-error-0x800f0906

Thoughts? Advice? Tweaks to the procedure? Thank you for your continued assistance, in advance.

**Comment by terence1981s** [comment]
@Bert-Proesmans yeah, I know a clean install would definitely solve the problem, but there are so many application plugins and add-ons that I no longer know where the licenses are or even where the installation files are. I am a video editor, you can imagine how many plug-ins and independent add-ons I've piled on to my Adobe Suite over the years. They literally number in the hundreds from Photoshop to Premiere to After Effects. 
A clean install would basically mean losing all of them, some of which I use regularly in my work. I usually take great care with my machine but a lightning strike caused a power outage which caused this crash, which was a particularly bad one since it was in the middle of some processor intensive stuff.
What do you guys think? Is a clean install my only option here?

**Comment by Zawodowiec1532** [comment]
Can you give dism.log after this Error 2? (StartComponentCleanup)
Atleast its diffrent error than before! :D

btw. Try do it in safe mode.

**Comment by terence1981s** [comment]
Here's the log:
[dism.log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1241496/dism.log.txt)
Did all the above steps both in safe mode and by rebooting into raised command prompt. Same results.

**Comment by terence1981s** [comment]
Also tried the steps in the two articles listed at the bottom of the last post with screengrabs, also in safe mode and again in (rebooted into) command prompt

**Comment by Bert-Proesmans** [comment]
Seems like dism couldn't open the wim file for restoring.. i actually wonder if the container index matters, because the media tools builds an install for each windows 10 version (pro, home, enterprise and student [i think]). it might be you have home edition installed so you'll have to pick index 2. -> this is guesswork since the log doesn't explain anything.

About `2017-08-21 19:12:21, Warning               DISM   DISM OS Provider: PID=14536 TID=3524 Unable to set the DLL search path to the servicing stack folder. C:\Windows may not point to a valid Windows folder. - CDISMOSServiceManager::Final_OnConnect`. 
Open regedit and browse to this collection`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\Version`. What is the value of the (only) key, it should have a path as value? Does the keyname match a foldername inside `C:\Windows\servicing\Version` ?

**Comment by terence1981s** [comment]
Hmm, that makes sense. I don't understand what I found in the places you asked me to look though:
![clipboard01rrrrrreg](https://user-images.githubusercontent.com/31148959/29597777-7d8e7fc0-87f7-11e7-8ea4-ba5206837679.jpg)
And in the windows folder:
![clipboard01sssssserv](https://user-images.githubusercontent.com/31148959/29597796-9ac20c06-87f7-11e7-910e-05f4158f5406.jpg)
![clipboard01vvvvvver](https://user-images.githubusercontent.com/31148959/29597797-9ac89026-87f7-11e7-8c4c-56cb731116a4.jpg)

**Comment by terence1981s** [comment]
Do I have to set a value for dism to recognise the windows boot source I created as source? Should there already be a value set or is there usually not?

**Comment by terence1981s** [comment]
@Bert-Proesmans , appreciate the continued assistance. Hope it doesn't take too much of your time.

**Comment by Bert-Proesmans** [comment]
According to your screenshots your folder layout is normal. I expected dism getting confused if multiple servicing versions would be defined. Maybe the contents of the folder which is used as registry value for the key `10.0.15063.410` is different? Below is a screenshot of the contents of the folder on my computer. (I have the same servicing version)
![contents](https://user-images.githubusercontent.com/2027877/29611746-0f3e0092-87ff-11e7-99d8-6dadf20de247.PNG)

I'm at the end of my knowledge here. The last 2 things i can suggest are the following.

Check the wim file contents by using `dism /get-wiminfo /wimfile:F:\sources\install.wim`. (change the path to point to your mounted install iso.) Remember the index value that matches the install container for your version of windows, which is pro or home or another derivate. Rerun `dism /Online /Cleanup-Image /RestoreHealth /Source:wim:F:\sources\install.wim:1 /limitaccess`, replace 1 with the correct index value. Try the command a second time if the first one still fails.

If that doesn't work run the windows setup again from the mounted install and do an inplace upgrade/restore. BUT i'm not sure to what extend your system will be changed and which effects it will have on your installed programs.

**Comment by terence1981s** [comment]
@Bert-Proesmans  thanks for the advice. I'll try it. But the restore keeps personal files and wipes installed programs and apps - I can't do that. So if the dism modifications don't work, I'll have to get used to playing HS without the deck tracker again, which will be a pity. It makes the game so much more involved, competitive and interesting to play (without having to resort to a pen and paper.

**Comment by terence1981s** [comment]
I'll leave the thread open for any of your fellow Windows geniuses who happen by, trip on a rock and fall down this rabbit hole.

**Comment by terence1981s** [comment]
@Bert-Proesmans  - I encountered a snag trying to follow that last try you gave me - in trying to find the right index, the dism operation returned the following error (this is after I mounted the ISO on H:\):
![clipboard01erererer](https://user-images.githubusercontent.com/31148959/29652506-4c02f9a4-88d8-11e7-85eb-50b566487d97.jpg)
I tried it again having extracted the entire contents of the ISO to a formatted thumbdrive (also H:\ but an actual drive instead of a virtual one this time) and the result was the same. Any idea what is causing this error?

**Comment by terence1981s** [comment]
I also checked my directory as you displayed (yours) above - I have the same 20 files, no differences.

**Comment by riQQ** [comment]
Have you checked, if there is a `install.wim` at `H:\sources\`?

**Comment by terence1981s** [comment]
Actually there isn't a 'install.wim' there. But there is a 'install.esd'. So, running the command returns 'File not found'.
Why isn't there a 'install.wim' in my iso image? How do I rectify this?

**Comment by terence1981s** [comment]
@riQQ the previous comment was in response to your question. Well spotted, by the way.

**Comment by Zawodowiec1532** [comment]
Just change in command .wim to .esd
esd is just newer version of wim

**Comment by terence1981s** [comment]
@ @Zawodowiec1532 Thanks, will try.

**Comment by terence1981s** [comment]
@Zawodowiec1532 ok, tried it multiple times with different indexes with the same error each time:
![clipboard01](https://user-images.githubusercontent.com/31148959/29808553-2f3f9bfa-8ccb-11e7-8eb6-8aed9e2e034b.jpg)

 I don't see how trying it in safe mode would find the source any better. Sigh.

**Comment by Bert-Proesmans** [comment]
Maybe something interferes with the mounting process. 
Copying the install.esd file to your desktop (where your user has full security control) and using it from there works?

**Comment by Zawodowiec1532** [comment]
https://www.tenforums.com/tutorials/29588-see-full-details-about-windows-10-iso-file.html

https://www.tenforums.com/tutorials/7808-use-dism-repair-windows-10-image.html

Here you have detailed tutorial with .esd/.wim and index checking.
Try this command again without `:esd:` prefix

If this not help, probably you can mount this image manually.
`Dism /Mount-Image /ImageFile:C:\test\images\myimage.esd /index:1 /MountDir:C:\test\offline`

and then use this path in /source without `:esd:`

btw. Have you tried troubleshooter in windows control panel?
https://www.howtogeek.com/wp-content/uploads/2016/06/img_576af51f161e5.png

**Comment by terence1981s** [comment]
@Zawodowiec1532 if you mean this:
![clipboard01](https://user-images.githubusercontent.com/31148959/29822012-8f517438-8cfc-11e7-9a9f-238a90e80aec.jpg)
then yes I have tried it already. No help.

I'm looking through the links you sent and trying to decipher them as best I can.

"Try this command again without :esd: prefix" - which command?

"If this not help, probably you can mount this image manually.
Dism /Mount-Image /ImageFile:C:\test\images\myimage.esd /index:1 /MountDir:C:\test\offline" - 
I assume you mean change C: to the drive letter of my image.

 I have tried doing it two ways previously - by using a physical USB for the image file so it does not need mounting and has its own drive letter and second, by using PowerISO to mount the ISO version of the image to a virtual drive. Both were unsuccessful.

**Comment by Zawodowiec1532** [comment]
Sorry, I don't know how I can help you. :(
If you find a solution, then post it here.

**Comment by riQQ** [comment]
Closing as this isn't a HDT issue and we are out of ideas.
