### ISSUE TITLE
HDT does not start

### ISSUE THREAD

**Issue by royard** [HearthSim/Hearthstone-Deck-Tracker#3497]
I switched computers at the end of Nov, installed HDT on my new computer and copied my old files over.  It worked well until Dec 9.  I tried to open it this morning and it does not start.  The hdt_log.txt is still dated Dec 9 so that probably won't help.  

During these days, I may have installed a "security update for Visual C++ 2005 SP1 Redistributable Package (KB2538242)" or updated my GeForce driver.  I'm on Win 10 Pro 1709 (16299.98).

Any help is appreciated - to be honest I don't really know how to play HS without HDT nowadays.  

----------------------------------------

Application Error log entry from event viewer:  

Faulting application name: HearthstoneDeckTracker.exe, version: 1.5.7.3362, time stamp: 0x5a2f45d4
Faulting module name: KERNELBASE.dll, version: 10.0.16299.15, time stamp: 0x2cd1ce3d
Exception code: 0xe0434352
Fault offset: 0x001008b2
Faulting process id: 0x1d08
Faulting application start time: 0x01d37351133ebdc2
Faulting application path: C:\Users\Ro\AppData\Local\HearthstoneDeckTracker\app-1.5.7-dev3362\HearthstoneDeckTracker.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 3de4b34b-86ae-4d3e-80d5-d3e3aaab468d
Faulting package full name: 
Faulting package-relative application ID: 

----------------------------------------

.Net Runtime Error log entry from event viewer:  

Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.Windows.UIElement.RegisterEvents(System.Type)
   at System.Windows.UIElement..cctor()

Exception Info: System.TypeInitializationException
   at System.Windows.FrameworkElement..cctor()

Exception Info: System.TypeInitializationException
   at System.Windows.StaticResourceExtension.FindResourceInAppOrSystem(System.IServiceProvider, Boolean, Boolean)
   at System.Windows.StaticResourceExtension.FindResourceInEnviroment(System.IServiceProvider, Boolean, Boolean)
   at System.Windows.StaticResourceExtension.TryProvideValueInternal(System.IServiceProvider, Boolean, Boolean)
   at System.Windows.ResourceDictionary.SetOptimizedStaticResources(System.Collections.Generic.IList`1<System.Object>, System.IServiceProvider, System.Windows.StaticResourceExtension)
   at System.Windows.ResourceDictionary.SetKeys(System.Collections.Generic.IList`1<System.Windows.Baml2006.KeyRecord>, System.IServiceProvider)
   at System.Windows.ResourceDictionary.SetDeferrableContent(System.Windows.DeferrableContent)
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext+<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__297_0(System.Object, System.Object)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(System.Object, System.Object)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(System.Xaml.XamlMember, System.Object, System.Object)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(System.Object, System.Xaml.XamlMember, System.Object)

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadComponent(System.Object, System.Uri)
   at Hearthstone_Deck_Tracker.App.InitializeComponent()
   at Hearthstone_Deck_Tracker.App.Main()

**Comment by riQQ** [comment]
Which files did you copy exactly? Have you tried reinstalling?

**Comment by Zawodowiec1532** [comment]
`Exception Info: System.IO.FileNotFoundException`

You missing some file. Try install stable version 1.5.6 instead of dev build.

**Comment by royard** [comment]
Thanks for looking into this!

I copied the [user]/appdata/local and roaming folders (hearthsim and heathstonedeacktracker).  They worked for more than 10 days, including multiple restarts.  

I tried uninstalling and reinstalling and it did not work.  

I tried both 1.5.6 and the most recent dev build and neither works.  This is what I get for using 1.5.6:  







Application Error log entry from event viewer:

Faulting application name: HearthstoneDeckTracker.exe, version: 1.5.6.3341, time stamp: 0x5a28c08a
Faulting module name: KERNELBASE.dll, version: 10.0.16299.15, time stamp: 0x2cd1ce3d
Exception code: 0xe0434352
Fault offset: 0x001008b2
Faulting process id: 0x3774
Faulting application start time: 0x01d3739106952e65
Faulting application path: C:\Users\Ro\AppData\Local\HearthstoneDeckTracker\app-1.5.6\HearthstoneDeckTracker.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: ea067fdd-1641-4e91-890a-adf78a4868fa
Faulting package full name: 
Faulting package-relative application ID: 

---------------------------

.Net Runtime Error log entry from event viewer:

Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.Windows.UIElement.RegisterEvents(System.Type)
   at System.Windows.UIElement..cctor()

Exception Info: System.TypeInitializationException
   at System.Windows.FrameworkElement..cctor()

Exception Info: System.TypeInitializationException
   at System.Windows.StaticResourceExtension.FindResourceInAppOrSystem(System.IServiceProvider, Boolean, Boolean)
   at System.Windows.StaticResourceExtension.FindResourceInEnviroment(System.IServiceProvider, Boolean, Boolean)
   at System.Windows.StaticResourceExtension.TryProvideValueInternal(System.IServiceProvider, Boolean, Boolean)
   at System.Windows.ResourceDictionary.SetOptimizedStaticResources(System.Collections.Generic.IList`1<System.Object>, System.IServiceProvider, System.Windows.StaticResourceExtension)
   at System.Windows.ResourceDictionary.SetKeys(System.Collections.Generic.IList`1<System.Windows.Baml2006.KeyRecord>, System.IServiceProvider)
   at System.Windows.ResourceDictionary.SetDeferrableContent(System.Windows.DeferrableContent)
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext+<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__297_0(System.Object, System.Object)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(System.Object, System.Object)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(System.Xaml.XamlMember, System.Object, System.Object)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(System.Object, System.Xaml.XamlMember, System.Object)

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadComponent(System.Object, System.Uri)
   at Hearthstone_Deck_Tracker.App.InitializeComponent()
   at Hearthstone_Deck_Tracker.App.Main()

**Comment by azeier** [comment]
Try running the [.NET Framework Repair Tool](https://www.microsoft.com/en-us/download/details.aspx?id=30135).

**Comment by royard** [comment]
I tried the .NET Framework Repair Tool mentioned above - the diagnostic did not really say anything and HDT still won't start.

**Comment by riQQ** [comment]
Stack trace may be the same as in #2201.
Can you check / post the contents of the folder `%LOCALAPPDATA%\HearthstoneDeckTracker\<insert-latest-version-here>\Images`

**Comment by royard** [comment]
This is my HDT folder structure (including the image folder):

https://imgur.com/a/dbwMc

**Comment by riQQ** [comment]
Does the `Image` folder contain the icons `HearthstoneDeckTracker.ico` and `HearthstoneDeckTracker16.ico`?

If yes:
Turn on Windows Error Reporting: Create this registry key `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps`, start HDT, and upload the crash dump from `%LocalAppData%\CrashDumps`.
By deleting the registry key, crash dump creation is turned off again.

**Comment by Zawodowiec1532** [comment]
Is it the same?
https://i.imgur.com/iDXrXjh.png

Btw. This is kinda strange, it says you have `Framework Version: v4.0.30319`, but Windows 10 have build-in version 4.6
Can you check what it's wrote about it in your hdt_log?

ps. You should also try steps from Microsoft webpage:

> There could be a system file corruption on your computer. Try performing a SFC scan and check if the issue persist.

> **Method 1:** System File checker (SFC) scan is done to check if there are any corrupted system files that could be causing this issue. Kindly follow the below given steps:
> Press **Windows key + X**, select **Command prompt (Admin)** to bring up elevated Command prompt.
> In Command prompt type **sfc /scannow** and press enter.
> **Restart** the computer.

> **Method 2:** You can try re-registering kernelbase.dll and check.
>  
> Press **Windows Key + X** and click on **Command Prompt (Admin)**
> Type **regsvr32 KERNELBASE.dll** and hit **Enter**.
> **Restart** your computer and check.

**Comment by riQQ** [comment]
@Zawodowiec1532 all .NET 4.x versions are in-place updates, so the version number is always the same

**Comment by Zawodowiec1532** [comment]
@riQQ Yeah, you are right. ^^

**Comment by royard** [comment]
Thank you for your continued attention - 

- the Image folder contain the icons HearthstoneDeckTracker.ico and HearthstoneDeckTracker16.ico.

- sfc /scannow did not reveal any errors

- regsvr32 KERNELBASE.dll gave me an error "The module 'KERNALBASE.dll' was loaded but the entry-point DllRegisterServer was not found. Make sure that 'KERNELBASE.dll' is a valid DLL or OCX file and then try again." but information from internet searches suggest that this may not be a KERNALBASE.dll issue

- crash dump is at this link:
https://ufile.io/gj8nk

**Comment by Zawodowiec1532** [comment]
@royard What about new release? Try clean install it and don't copy any files. Also be sure you have all windows updates installed.

ps. You can also try checking .NET Framework 4.7 checkbox in `Control Panel -> Programs -> Windows Functions` Like on screenshot: https://i.imgur.com/kuIu723.png (Restart PC after).

**Comment by riQQ** [comment]
Okay, the underlying error is `Could not load file or assembly 'UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.`

**Comment by riQQ** [comment]
Looks like .NET Framework installation or Windows is broken.

**Comment by royard** [comment]
Thank you for keep looking into this.  I ended up clean-refreshing my Win 10 (wasn't too painful as I still have all the backup stuff from my recent switch) and everything is working now.  Really appreciate the help of everyone in this thread!
