### ISSUE TITLE
Uneven permission December 2017

### ISSUE THREAD

**Issue by AkiRyuuTo** [HearthSim/Hearthstone-Deck-Tracker#3504]
Hello, returning user of the app here since i got a new computer, downloaded the app 5 times already trying to make it work, ran both Battle.net and HDT in admin mode but it still said i had uneven permissions. Here's the newest log that's in my appdata folder. Thanks for the future help.

12:09:45 AM|Info|Core.Initialize >> HDT: 1.5.9.3382, Operating System: Windows 10 Pro 10586, .NET Framework: 394254
12:09:45 AM|Info|Updater.StartupUpdateCheck >> Checking for updates
12:09:45 AM|Info|Updater.GetReleaseUrl >> Downloading releases file
12:09:46 AM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
12:09:56 AM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
12:09:59 AM|Info|Updater.SquirrelUpdate >> No new updated available
12:09:59 AM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
12:09:59 AM|Info|ThemeManager.LoadThemes >> Found theme: classic
12:09:59 AM|Info|ThemeManager.LoadThemes >> Found theme: dark
12:09:59 AM|Info|ThemeManager.LoadThemes >> Found theme: frost
12:09:59 AM|Info|ThemeManager.LoadThemes >> Found theme: minimal
12:09:59 AM|Info|GameV2.Reset >> -------- Reset ---------
12:10:02 AM|... 1 duplicate messages
12:10:02 AM|Info|BackupManager.Run >> Running BackupManager
12:10:02 AM|Info|BackupManager.Run >> Deleting old backup: Backup_24092017.zip
12:10:02 AM|Info|BackupManager.Run >> Creating backup for today
12:10:03 AM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
12:10:03 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:10:03 AM|Info|LogWatcherManager.Start >> Using Hearthstone log directory 'C:\Program Files (x86)\Hearthstone\Logs'
12:10:03 AM|Info|LogWatcherManager.OnLogFileFound >> LoadingScreen
12:10:03 AM|Info|LogWatcherManager.OnLogFileFound >> Rachelle
12:10:03 AM|Info|ApiWrapper.UpdateAccountStatus >> Checking account status...
12:10:03 AM|Info|GameV2.CurrentMode >> LOGIN
12:10:03 AM|Info|HsReplayDecks.Load >> Loaded from disk: Count=2697, ServerTS=12/15/2017 6:21:32 PM, Downloaded=12/16/2017 3:02:19 AM Age=21:07:44.1166136
12:10:03 AM|Info|HsReplayDecks.Load >> Complete: Count=2697, ServerTS=12/15/2017 6:21:32 PM, Downloaded=12/16/2017 3:02:19 AM Age=21:07:44.1180063
12:10:05 AM|Info|ApiWrapper.UpdateAccountStatus >> Id=0, Username=, Status=Anonymous
12:10:08 AM|Info|OverlayWindow.SetTopmost >> Could not set overlay as topmost
12:10:09 AM|Info|LogWatcherManager.OnLogFileFound >> FullScreenFX
12:10:23 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:10:23 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:10:28 AM|Info|OverlayWindow.SetTopmost >> Could not set overlay as topmost
12:10:43 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:10:44 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:11:04 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:11:04 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:11:24 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:11:24 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:11:40 AM|Info|GameV2.CurrentMode >> HUB
12:11:40 AM|Info|LoadingScreenHandler.CheckMirrorStatus >> Mirror status: Error
12:11:40 AM|Error|LoadingScreenHandler.CheckMirrorStatus >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at HearthMirror.ProcessView..ctor(Process proc)
   at HearthMirror.Mirror.get_View()
   at HearthMirror.Status.GetStatus()
12:11:44 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:11:44 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:12:04 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:12:05 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:12:25 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:12:25 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:12:45 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:12:45 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:13:05 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:13:05 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:13:25 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:13:26 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:13:46 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:13:46 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:14:06 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:14:06 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:14:26 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:14:26 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:14:47 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:14:47 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:15:07 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:15:07 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:15:27 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:15:27 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:15:47 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:15:47 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:16:08 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:16:08 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:16:28 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:16:28 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:16:48 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:16:48 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()
12:17:08 AM|Info|Helper.GetCurrentRegion >> Region (from config): 
12:17:08 AM|Error|Helper.VerifyHearthstonePath >> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Hearthstone_Deck_Tracker.Helper.VerifyHearthstonePath()

**Comment by riQQ** [comment]
Have you checked #2738 for potential workarounds?

**Comment by AkiRyuuTo** [comment]
Yes, i have done everything in the thread prior to me posting my complaint.

Virtually nothing had worked on me, though i haven't tried downloading an
older version of HDT.

**Comment by Abaporu** [comment]
OK, i got the answer: Go to Battle.net app on desktop, properties, them security. Find the INTERACTIVE item and change the settings to have Full Access to the app. It worked for me, because i think the problem here is the permission that u changed somewhere you dont know. And neither me

**Comment by riQQ** [comment]
@Abaporu what do you mean by `interactive item`?

**Comment by azeier** [comment]
Closing in favor of #2738
