### ISSUE TITLE
Collection won't update

### ISSUE THREAD

**Issue by GMRedBear** [HearthSim/Hearthstone-Deck-Tracker#3704]
## Bug report
My Collection won't update
### Expected Behavior

Collection to update whenever I enter the Collection or Pack Screan
### Actual Behavior

No update to collection happens on HSReplay
### Steps to reproduce behavior

Ongoing as hasn't updated for 33days
### Log/Screenshots

```
7:23:25 PM|Info|Core.Initialize >> HDT: 1.6.7.3635, Operating System: Windows 10 Home 17134, .NET Framework: 461808
7:23:25 PM|Info|Updater.StartupUpdateCheck >> Checking for updates
7:23:25 PM|Info|Updater.GetReleaseUrl >> Downloading releases file
7:23:26 PM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
7:23:28 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
7:23:30 PM|Info|Updater.SquirrelUpdate >> No new updated available
7:23:30 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
7:23:32 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
7:23:32 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
7:23:32 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
7:23:32 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
7:23:32 PM|Info|GameV2.Reset >> -------- Reset ---------
7:23:41 PM|Info|MainWindow.SelectDeck >> Switched to deck: Custom Hunter (v1.0)
7:23:41 PM|Info|GameV2.Reset >> -------- Reset ---------
7:23:43 PM|Info|BackupManager.Run >> Running BackupManager
7:23:43 PM|Info|BackupManager.Run >> Backup for today already exists
7:23:43 PM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
7:23:44 PM|Info|Helper.GetCurrentRegion >> Region: EU
7:23:44 PM|Info|BackupManager.Run >> Running BackupManager
7:23:44 PM|Info|BackupManager.Run >> Backup for today already exists
7:23:44 PM|Info|LogWatcherManager.Start >> Using Hearthstone log directory 'C:\Program Files (x86)\Hearthstone\Logs'
19:23:45|Info|LogWatcherManager.OnLogFileFound >> LoadingScreen
19:23:45|Info|LogWatcherManager.OnLogFileFound >> Rachelle
7:23:45 PM|Info|HSReplayNetOAuth.UpdateAccountData >> Updating account data...
7:23:45 PM|Info|HSReplayNetOAuth.UpdateToken >> Refreshing token data...
19:23:45|Info|LogWatcherManager.OnLogFileFound >> FullScreenFX
19:23:45|Info|LogWatcherManager.OnLogFileFound >> Power
7:23:45 PM|Info|HsReplayDecks.Load >> Loaded from disk: Count=3089, ServerTS=6/13/2018 3:51:31 PM, Downloaded=6/13/2018 6:36:35 PM Age=00:47:10.1413724
7:23:45 PM|Info|HsReplayDecks.Load >> Complete: Count=3089, ServerTS=6/13/2018 3:51:31 PM, Downloaded=6/13/2018 6:36:35 PM Age=00:47:10.1413724
7:23:45 PM|Info|GameV2.CurrentMode >> TOURNAMENT
7:23:45 PM|Info|GameV2.CurrentMode >> HUB
7:23:45 PM|Info|GameV2.CurrentMode >> COLLECTIONMANAGER
7:23:45 PM|Info|GameV2.CurrentMode >> HUB
7:23:45 PM|Info|GameV2.CurrentMode >> PACKOPENING
7:23:45 PM|Info|GameV2.CurrentMode >> HUB
7:23:45 PM|Info|GameV2.CurrentMode >> COLLECTIONMANAGER
7:23:45 PM|Info|GameV2.CurrentMode >> HUB
7:23:46 PM|Error|HSReplayNetOAuth.UpdateToken >> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HSReplay.WebClient.<SendWebRequestAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HSReplay.WebClient.<PostAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HSReplay.OAuth.OAuthClient.<RefreshToken>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.HsReplay.HSReplayNetOAuth.<UpdateToken>d__32.MoveNext()
7:23:46 PM|Info|HSReplayNetOAuth.UpdateToken >> Fetching new token...
7:23:46 PM|Error|HSReplayNetOAuth.UpdateToken >> System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HSReplay.WebClient.<SendWebRequestAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HSReplay.WebClient.<PostAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HSReplay.OAuth.OAuthClient.<GetToken>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.HsReplay.HSReplayNetOAuth.<UpdateToken>d__32.MoveNext()
7:23:46 PM|Error|HSReplayNetOAuth.UpdateAccountData >> Could not update token data
7:23:50 PM|Info|OverlayWindow.SetTopmost >> Could not set overlay as topmost
7:43:28 PM|... 1 duplicate messages
7:43:28 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
7:43:29 PM|Info|Updater.SquirrelUpdate >> No new updated available
7:46:49 PM|Info|GameV2.CurrentMode >> FATAL_ERROR
8:03:28 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
8:03:29 PM|Info|Updater.SquirrelUpdate >> No new updated available
```

**Comment by GMRedBear** [comment]
I hope this is what you need I'm very "unskilled" at this part of computing

**Comment by riQQ** [comment]
Yeah, that's fine.

**Comment by azeier** [comment]
Try logging out and in again under options.

**Comment by GMRedBear** [comment]
Thanks that was the issue.

**Comment by x-ProgrammEd-x** [comment]
Hi, i have been encountering this since over a month now. Even multiple Re-Logins as stated in the error message didn't fix it :(. Any advice?

**Comment by riQQ** [comment]
@x-ProgrammEd-x make sure you are using the latest version
