### ISSUE TITLE
Issue after update to 1.6.9.3642 - corrupt deck stats - Invalid character- Hex value. Workaround found

### ISSUE THREAD

**Issue by Gezzap** [HearthSim/Hearthstone-Deck-Tracker#3730]
### Expected Behavior

After update that my deck stats would not be lost.
### Actual Behavior

After the update today -my deckstats file was considered corrupt. Same problem persisted with backup versions. I found a work around.
### Log/Screenshots
<!Log>
`6:27:58 AM|Info|Core.Initialize >> HDT: 1.6.9.3642, Operating System: Windows 10 Enterprise 17134, .NET Framework: 461808
6:27:58 AM|Info|Updater.StartupUpdateCheck >> Checking for updates
6:27:58 AM|Info|Updater.GetReleaseUrl >> Downloading releases file
6:28:00 AM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
6:28:02 AM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
6:28:05 AM|Info|Updater.SquirrelUpdate >> No new updated available
6:28:05 AM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
6:28:05 AM|Info|ThemeManager.LoadThemes >> Found theme: classic
6:28:05 AM|Info|ThemeManager.LoadThemes >> Found theme: dark
6:28:05 AM|Info|ThemeManager.LoadThemes >> Found theme: frost
6:28:05 AM|Info|ThemeManager.LoadThemes >> Found theme: minimal
6:28:05 AM|Info|GameV2.Reset >> -------- Reset ---------
6:28:06 AM|Error|DeckStatsList.Load >> System.InvalidOperationException: There is an error in XML document (41191, 35). ---> System.Xml.XmlException: '', hexadecimal value 0x01, is an invalid character. Line 41191, position 35.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(Int32 startPos, Boolean expand, StringBuilder internalSubsetBuilder, Int32& charCount, EntityType& entityType)
   at System.Xml.XmlTextReaderImpl.ParseCharRefInline(Int32 startPos, Int32& charCount, EntityType& entityType)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.ReadElementString()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read5_GameServerInfo(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read13_GameStats(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read14_DeckStats(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read15_DeckStatsList(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read16_DeckStatsList()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Hearthstone_Deck_Tracker.XmlManager`1.Load(String path)
   at Hearthstone_Deck_Tracker.Stats.DeckStatsList.Load()
6:28:06 AM|Info|BackupManager.TryRestore >> Restoring latest backup for DeckStats.xml...
6:28:07 AM|Error|BackupManager.TryRestore >> System.InvalidOperationException: There is an error in XML document (41184, 32). ---> System.Xml.XmlException: '', hexadecimal value 0x01, is an invalid character. Line 41184, position 32.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(Int32 startPos, Boolean expand, StringBuilder internalSubsetBuilder, Int32& charCount, EntityType& entityType)
   at System.Xml.XmlTextReaderImpl.ParseCharRefInline(Int32 startPos, Int32& charCount, EntityType& entityType)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.ReadElementString()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read5_GameServerInfo(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read13_GameStats(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read14_DeckStats(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read15_DeckStatsList(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read16_DeckStatsList()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Hearthstone_Deck_Tracker.XmlManager`1.Load(String path)
   at Hearthstone_Deck_Tracker.Utility.BackupManager.TryRestore[T](String file)
6:28:07 AM|Info|BackupManager.TryRestore >> Restoring second to latest backup for DeckStats.xml...
6:28:07 AM|Error|BackupManager.TryRestore >> System.InvalidOperationException: There is an error in XML document (41184, 32). ---> System.Xml.XmlException: '', hexadecimal value 0x01, is an invalid character. Line 41184, position 32.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(Int32 startPos, Boolean expand, StringBuilder internalSubsetBuilder, Int32& charCount, EntityType& entityType)
   at System.Xml.XmlTextReaderImpl.ParseCharRefInline(Int32 startPos, Int32& charCount, EntityType& entityType)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.ReadElementString()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read5_GameServerInfo(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read13_GameStats(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read14_DeckStats(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read15_DeckStatsList(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read16_DeckStatsList()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Hearthstone_Deck_Tracker.XmlManager`1.Load(String path)
   at Hearthstone_Deck_Tracker.Utility.BackupManager.TryRestore[T](String file)
6:28:07 AM|Info|ErrorManager.AddError >> New error: DeckStats.xml was corrupted but restored from the latest backup.
This is likely due to an unexpected shutdown.
Backups are generated on the first start of each day, so there may be lost data.
We are very sorry for the inconvenience. :(`

### This is the corrupt area in the deckstats file
          <ServerInfo>
            <Address>checkFirstFr</Address>
            <AuroraPassword>&#x1;&#x0;:&#x0;&#x0;&#x0;</AuroraPassword>
            <ClientHandle>1627042</ClientHandle>
            <GameHandle>9896301</GameHandle>
            <Mission>2</Mission>
            <Port>3724</Port>
            <Resumable>true</Resumable>
            <SpectatorMode>false</SpectatorMode>
            <SpectatorPassword>&#x1;&#x0;:&#x0;&#x0;&#x0;</SpectatorPassword>
            <Version>&#x1;&#x0;:&#x0;&#x0;&#x0;</Version>
          </ServerInfo>

### The workaround is to delete this password information from the deckstats file as per below
          <ServerInfo>
            <Address>checkFirstFr</Address>
            <AuroraPassword>none</AuroraPassword>
            <ClientHandle>1627042</ClientHandle>
            <GameHandle>9896301</GameHandle>
            <Mission>2</Mission>
            <Port>3724</Port>
            <Resumable>true</Resumable>
            <SpectatorMode>false</SpectatorMode>
            <SpectatorPassword>none</SpectatorPassword>
            <Version>none</Version>
          </ServerInfo>

Apologies in advance for formatting issues - the copy paste from log glitches in here. Would appreciate advice on how to make the editor behave here

**Comment by azeier** [comment]
A potential (preventative) solution to this might be to add a check in HearthMirror that read values (mostly strings I suppose) don't contain null characters, and throwing an exception in the case that they do to invalidate the entire read dataset.
