### ISSUE TITLE
Hearthstone Deck Tracker won't open installer

### ISSUE THREAD

**Issue by xSteen** [HearthSim/Hearthstone-Deck-Tracker#3734]
## Bug report
After I download the HDT installer and click to open it, nothing happens.
### Expected Behavior
Open the installer and begin installing the program.

### Actual Behavior
Nothing. One windows looking icon pops up for half a second on the toolbar then nothing happens.

Below is the SquirrelSetup - Notepad
2018-07-12 18:25:01> Program: Starting Squirrel Updater: --install .
2018-07-12 18:25:01> Program: Starting install, writing to C:\Users\Derrick\AppData\Local\SquirrelTemp
2018-07-12 18:25:01> Program: About to install to: C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker
2018-07-12 18:25:01> Program: Install path C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker already exists, burning it to the ground
2018-07-12 18:25:02> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-07-12 18:25:02> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2018-07-12 18:25:02> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Derrick\AppData\Local\SquirrelTemp
2018-07-12 18:25:02> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-07-12 18:25:02> ApplyReleasesImpl: Writing files to app directory: C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\app-1.6.9
2018-07-12 18:25:02> LogHost: Rigging execution stub for HearthstoneDeckTracker_ExecutionStub.exe to C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\HearthstoneDeckTracker.exe
2018-07-12 18:25:04> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\app-1.6.9\HearthstoneDeckTracker.exe]
2018-07-12 18:25:05> ApplyReleasesImpl: Starting fixPinnedExecutables
2018-07-12 18:25:05> ApplyReleasesImpl: Examining Pin: Battle.net Launcher - Shortcut.lnk
2018-07-12 18:25:05> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2018-07-12 18:25:05> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2018-07-12 18:25:05> ApplyReleasesImpl: Examining Pin: HearthArena Companion.lnk
2018-07-12 18:25:05> ApplyReleasesImpl: Examining Pin: League of Legends.lnk
2018-07-12 18:25:05> ApplyReleasesImpl: Fixing up tray icons
2018-07-12 18:25:05> ApplyReleasesImpl: cleanDeadVersions: for version 1.6.9
2018-07-12 18:25:05> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.6.9
2018-07-12 18:25:56> Program: Starting Squirrel Updater: --install .
2018-07-12 18:25:56> Program: Starting install, writing to C:\Users\Derrick\AppData\Local\SquirrelTemp
2018-07-12 18:25:56> Program: About to install to: C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker
2018-07-12 18:25:56> Program: Install path C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker already exists, burning it to the ground
2018-07-12 18:25:56> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-07-12 18:25:56> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2018-07-12 18:25:56> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Derrick\AppData\Local\SquirrelTemp
2018-07-12 18:25:56> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-07-12 18:25:56> ApplyReleasesImpl: Writing files to app directory: C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\app-1.6.9
2018-07-12 18:25:57> LogHost: Rigging execution stub for HearthstoneDeckTracker_ExecutionStub.exe to C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\HearthstoneDeckTracker.exe
2018-07-12 18:25:59> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\app-1.6.9\HearthstoneDeckTracker.exe]
2018-07-12 18:26:02> ApplyReleasesImpl: Starting fixPinnedExecutables
2018-07-12 18:26:02> ApplyReleasesImpl: Examining Pin: Battle.net Launcher - Shortcut.lnk
2018-07-12 18:26:02> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2018-07-12 18:26:02> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2018-07-12 18:26:02> ApplyReleasesImpl: Examining Pin: HearthArena Companion.lnk
2018-07-12 18:26:02> ApplyReleasesImpl: Examining Pin: League of Legends.lnk
2018-07-12 18:26:02> ApplyReleasesImpl: Fixing up tray icons
2018-07-12 18:26:02> ApplyReleasesImpl: cleanDeadVersions: for version 1.6.9
2018-07-12 18:26:02> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.6.9
2018-07-12 18:26:40> Program: Starting Squirrel Updater: --install .
2018-07-12 18:26:40> Program: Starting install, writing to C:\Users\Derrick\AppData\Local\SquirrelTemp
2018-07-12 18:26:40> Program: About to install to: C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker
2018-07-12 18:26:40> Program: Install path C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker already exists, burning it to the ground
2018-07-12 18:26:41> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-07-12 18:26:41> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2018-07-12 18:26:41> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Derrick\AppData\Local\SquirrelTemp
2018-07-12 18:26:41> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-07-12 18:26:41> ApplyReleasesImpl: Writing files to app directory: C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\app-1.6.9
2018-07-12 18:26:41> LogHost: Rigging execution stub for HearthstoneDeckTracker_ExecutionStub.exe to C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\HearthstoneDeckTracker.exe
2018-07-12 18:26:43> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\app-1.6.9\HearthstoneDeckTracker.exe]
2018-07-12 18:26:44> ApplyReleasesImpl: Starting fixPinnedExecutables
2018-07-12 18:26:44> ApplyReleasesImpl: Examining Pin: Battle.net Launcher - Shortcut.lnk
2018-07-12 18:26:44> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2018-07-12 18:26:44> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2018-07-12 18:26:44> ApplyReleasesImpl: Examining Pin: HearthArena Companion.lnk
2018-07-12 18:26:44> ApplyReleasesImpl: Examining Pin: League of Legends.lnk
2018-07-12 18:26:44> ApplyReleasesImpl: Fixing up tray icons
2018-07-12 18:26:44> ApplyReleasesImpl: cleanDeadVersions: for version 1.6.9
2018-07-12 18:26:44> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.6.9
2018-07-12 18:26:49> Program: Starting Squirrel Updater: --install . --rerunningWithoutUAC
2018-07-12 18:26:49> Program: Starting install, writing to C:\Users\Derrick\AppData\Local\SquirrelTemp
2018-07-12 18:26:49> Program: About to install to: C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker
2018-07-12 18:26:49> Program: Install path C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker already exists, burning it to the ground
2018-07-12 18:26:50> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-07-12 18:26:50> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2018-07-12 18:26:50> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Derrick\AppData\Local\SquirrelTemp
2018-07-12 18:26:50> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-07-12 18:26:50> ApplyReleasesImpl: Writing files to app directory: C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\app-1.6.9
2018-07-12 18:26:51> LogHost: Rigging execution stub for HearthstoneDeckTracker_ExecutionStub.exe to C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\HearthstoneDeckTracker.exe
2018-07-12 18:26:52> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\app-1.6.9\HearthstoneDeckTracker.exe]
2018-07-12 18:26:53> ApplyReleasesImpl: Starting fixPinnedExecutables
2018-07-12 18:26:53> ApplyReleasesImpl: Examining Pin: Battle.net Launcher - Shortcut.lnk
2018-07-12 18:26:53> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2018-07-12 18:26:53> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2018-07-12 18:26:53> ApplyReleasesImpl: Examining Pin: HearthArena Companion.lnk
2018-07-12 18:26:53> ApplyReleasesImpl: Examining Pin: League of Legends.lnk
2018-07-12 18:26:53> ApplyReleasesImpl: Fixing up tray icons
2018-07-12 18:26:53> ApplyReleasesImpl: cleanDeadVersions: for version 1.6.9
2018-07-12 18:26:53> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.6.9
2018-07-12 18:27:06> Program: Starting Squirrel Updater: --install .
2018-07-12 18:27:06> Program: Starting install, writing to C:\Users\Derrick\AppData\Local\SquirrelTemp
2018-07-12 18:27:06> Program: About to install to: C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker
2018-07-12 18:27:06> Program: Install path C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker already exists, burning it to the ground
2018-07-12 18:27:07> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-07-12 18:27:07> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2018-07-12 18:27:07> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Derrick\AppData\Local\SquirrelTemp
2018-07-12 18:27:07> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-07-12 18:27:07> ApplyReleasesImpl: Writing files to app directory: C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\app-1.6.9
2018-07-12 18:27:08> LogHost: Rigging execution stub for HearthstoneDeckTracker_ExecutionStub.exe to C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\HearthstoneDeckTracker.exe
2018-07-12 18:27:10> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Derrick\AppData\Local\HearthstoneDeckTracker\app-1.6.9\HearthstoneDeckTracker.exe]
2018-07-12 18:27:10> ApplyReleasesImpl: Starting fixPinnedExecutables
2018-07-12 18:27:10> ApplyReleasesImpl: Examining Pin: Battle.net Launcher - Shortcut.lnk
2018-07-12 18:27:10> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2018-07-12 18:27:10> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2018-07-12 18:27:10> ApplyReleasesImpl: Examining Pin: HearthArena Companion.lnk
2018-07-12 18:27:10> ApplyReleasesImpl: Examining Pin: League of Legends.lnk
2018-07-12 18:27:10> ApplyReleasesImpl: Fixing up tray icons
2018-07-12 18:27:10> ApplyReleasesImpl: cleanDeadVersions: for version 1.6.9
2018-07-12 18:27:10> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.6.9
2018-07-12 18:27:11> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.InvalidAsynchronousStateException: An error occurred invoking the method.  The destination thread no longer exists.
   at System.Windows.Forms.Control.WaitForWaitHandle(WaitHandle waitHandle)
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at Squirrel.Update.AnimatedGifWindow.<>c__DisplayClass2_1.<ShowWindow>b__2()
   at System.Threading.CancellationToken.ActionToActionObjShunt(Object obj)
   at System.Threading.CancellationCallbackInfo.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationCallbackInfo.ExecuteCallback()
   at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork(CancellationCallbackCoreWorkArguments args)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.Cancel()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.ComponentModel.InvalidAsynchronousStateException: An error occurred invoking the method.  The destination thread no longer exists.
   at System.Windows.Forms.Control.WaitForWaitHandle(WaitHandle waitHandle)
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at Squirrel.Update.AnimatedGifWindow.<>c__DisplayClass2_1.<ShowWindow>b__2()
   at System.Threading.CancellationToken.ActionToActionObjShunt(Object obj)
   at System.Threading.CancellationCallbackInfo.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationCallbackInfo.ExecuteCallback()
   at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork(CancellationCallbackCoreWorkArguments args)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)<---

Any help would be greatly appreciated

**Comment by riQQ** [comment]
Is there anything in the Windows event viewer: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#windows-log-files?

**Comment by xSteen** [comment]
I found a fix. Apparently there was one stray windows update that didn't get installed for the framework. Installed the one update and it worked.

**Comment by riQQ** [comment]
Good, thanks for reporting back.
