### ISSUE TITLE
HDT won't start [Windows 10]

### ISSUE THREAD

**Issue by ritual315** [HearthSim/Hearthstone-Deck-Tracker#3745]
Hi. I got the attached crash report several times on Windows 10. I've always used HDT on Win 10 until some months ago it stopped working

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MahApps.Metro.Controls.Flyout.OverrideFlyoutResources(ResourceDictionary resources, Boolean accent)
   at MahApps.Metro.Controls.Flyout.ChangeFlyoutTheme(Accent windowAccent, AppTheme windowTheme)
   at MahApps.Metro.Controls.Flyout.UpdateFlyoutTheme()
   at MahApps.Metro.Controls.Flyout.<.ctor>b__93_0(Object sender, RoutedEventArgs args)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by riQQ** [comment]
Could be a broken plugin. Try disabling / removing them.

**Comment by ritual315** [comment]
I can’t enter HDT to disable or remove plugins. Is there another way to do it?
Il 5 ago 2018, 18:53 +0200, riQQ <notifications@github.com>, ha scritto:

**Comment by riQQ** [comment]
Manually edit the file `%appdata%\HearthstoneDeckTracker\plugins.xml`
