### ISSUE TITLE
Crashing at start up version 1.5.11 and later

### ISSUE THREAD

**Issue by Yezhe1** [HearthSim/Hearthstone-Deck-Tracker#3776]
## Bug report
Crashing at start up version 1.5.11 and later

### Expected Behavior
Normal start

### Actual Behavior
Crashing at start up

### Log/Screenshots
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'Hearthstone_Deck_Tracker.FlyoutControls.OptionsMain' that matches the specified binding constraints threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Не удается найти указанный файл.
   at Hearthstone_Deck_Tracker.Utility.JsonSerializer`1.Load()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Hearthstone_Deck_Tracker.FlyoutControls.Options.HSReplay.HSReplayAccount.get_IsPremiumUser()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.InitializeComponent()
   at Hearthstone_Deck_Tracker.Windows.MainWindow..ctor()
   at Hearthstone_Deck_Tracker.Core.<Initialize>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Yezhe1** [comment]
sorry for googletranslate(

**Comment by Yezhe1** [comment]
Setting .NET Framework 4.7 help me, sorry for disturbing

**Comment by riQQ** [comment]
No worries, thanks for posting the solution.
