### ISSUE TITLE
Tracker does not react to any HS activity

### ISSUE THREAD

**Issue by alexbzg** [HearthSim/Hearthstone-Deck-Tracker#3794]
If hdt runs as local user it shows uneven rights warning, if runs as administrator no warning is shown and  in both cases no reaction to any HS events. I'm using win 10 pro x64, build 17134.285.
local user log: 
[hdt_log_1537769313.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2409822/hdt_log_1537769313.txt)
administrator log:
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2409825/hdt_log.txt)

**Comment by riQQ** [comment]
```
9:08:38 AM|Warning|Core.Initialize >> HearthMirror Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at HearthMirror.ProcessView.GetExport(String name)
   at HearthMirror.Mirror.get_Root()
   at HearthMirror.Reflection.GetAccountIdInternal()
   at HearthMirror.Reflection.TryGetInternal[T](Func`1 action, Boolean clearCache)
```

And many similiar errors in the log when run with administrator. Logging has to be improved to diagnose this further.
