### ISSUE TITLE
HDT won't launch

### ISSUE THREAD

**Issue by ValourousOne** [HearthSim/Hearthstone-Deck-Tracker#3807]
Hello,

I'm a Hearthstone Deck Tracker user of about 2 years now. I've had minor issues in the past but nothing I couldn't solve.

Recently whenever I try to launch deck tracker, it doesn't open. No window opens. Nothing happens. I've also tried running as administrator.

Thinking back to a few days ago, I thought this could be related to when I did a system restore to undo some monitor drivers I installed (the time between install and restore was about 2 days), but I can't be sure. Otherwise I have no idea what could be causing this issue.

I tried looking around on the forum for more than an hour, tried out a few of the suggested fixes, like:
-Tried to reinstall/repair .Net framework (would not work, said it was already installed on the system)
-Tried several commands in command prompt including sfc /scannow and the kernel command

I understand that bug reports/logs may be important to solve problems like these but I have no idea how to create/find the bug report, so if you could walk me through that, and anything else I need to to fix this, I would really appreciate it.

Thank you in advance for your time and willingness to help.

**Comment by riQQ** [comment]
Check all the points stated here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by ValourousOne** [comment]
Hello riQQ, and thank you for the response.

I visited the above link and was unable to follow the first 2 options as my HDT won't launch. 

For windows log options, I was able to find a number of logs when filtering for application error and .NET runtime, but surprisingly none of them were related to HDT...

I was able to find my setup log and have attached it here:
[SquirrelSetup.log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2519349/SquirrelSetup.log)

Is there a chance my issue could be fixed by uninstalling and then reinstalling HDT?

**Comment by riQQ** [comment]
```
2018-10-19 21:16:50> Unhandled exception: System.ArgumentException: Value does not fall within the expected range.
   at Squirrel.Update.Program.ProcessStart(String exeName, String arguments, Boolean shouldWait)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
2018-10-20 07:32:28> Program: Starting Squirrel Updater: --processStart HearthstoneDeckTracker.exe
```

Deleting %LOCALAPPDATA%\HearthstoneDeckTracker should help. This doesn't affect you stats / settings.

**Comment by riQQ** [comment]
I don't know what happened. If it's a similar problem it'll help.

**Comment by Twinkielock** [comment]
I hate to necro this thread, but Google brought me here.  (To this specific thread)  I too had an issue with HDT not launching.   Just like the OP I also did a system restore.  Deleting the most recent entry in my Appdata folder did the trick. 

Hope this helps others.
