### ISSUE TITLE
HDT Crashes on startup

### ISSUE THREAD

**Issue by MattsP1993** [HearthSim/Hearthstone-Deck-Tracker#3869]
HDT crashes on startup and i get a crash report with following stacktrace:
System.IO.IOException: Die Datei oder das Verzeichnis ist beschädigt und nicht lesbar.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at HearthWatcher.LogReader.LogFileWatcher.FindEntryPoint(String logDirectory, String[] str) in C:\projects\hearthstone-deck-tracker\HearthWatcher\LogReader\LogFileWatcher.cs:line 207
   at HearthWatcher.LogWatcher.GetStartingPoint(String logDirectory) in C:\projects\hearthstone-deck-tracker\HearthWatcher\LogWatcher.cs:line 71
   at HearthWatcher.LogWatcher.<Start>d__18.MoveNext() in C:\projects\hearthstone-deck-tracker\HearthWatcher\LogWatcher.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Happens every time I try to restart it. I already tried reinstalling HDT, updated all my drivers, reinstalled Hearthstone, but no change.

[Crash report 1322019-102.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2859574/Crash.report.1322019-102.txt)

Windows event log
Programm HearthstoneDeckTracker.exe, Version 1.8.0.3804 kann nicht mehr unter Windows ausgeführt werden und wurde beendet. Überprüfen Sie den Problemverlauf in der Systemsteuerung "Sicherheit und Wartung", um nach weiteren Informationen zum Problem zu suchen.
 Prozess-ID: 33d0
 Startzeit: 01d4c29e4de0e285
 Beendigungszeit: 4294967295
 Anwendungspfad: C:\Users\matth\AppData\Local\HearthstoneDeckTracker\app-1.8.0\HearthstoneDeckTracker.exe
 Berichts-ID: 8f3886b8-3812-430e-9122-69524ffee857
 Vollständiger Name des fehlerhaften Pakets: 
 Auf das fehlerhafte Paket bezogene Anwendungs-ID:

**Comment by riQQ** [comment]
Go to the Hearthstone installation folder and its subfolder Logs. Delete all log files in this folder.

**Comment by MattsP1993** [comment]
Thanks for your quick reply!
Seems my Power.log file is corrupted and can't be deleted.

**Comment by MattsP1993** [comment]
We can close this thread. It seems my harddrive is broken and caused this problem.
Thank you for your help.
