### ISSUE TITLE
HDT Crash

### ISSUE THREAD

**Issue by ZaradPeremogu** [HearthSim/Hearthstone-Deck-Tracker#3878]
Доброго времени суток, недавно столкнулся с такой проблемой:
При попытке запустить HDT, вылетает ошибка на этапе запуска программы, вот с такими симптомами:
```
System.Windows.Markup.XamlParseException: The invocation of the constructor on type ‘Hearthstone_Deck_Tracker.Utility.HotKeys.HotKeyManager’ that matches the specified binding constraints threw an exception. —> System.TypeInitializationException: The type initializer for ‘Hearthstone_Deck_Tracker.Utility.HotKeys.HotKeyManager’ threw an exception. —> System.BadImageFormatException: Could not load file or assembly ‘System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089’ or one of its dependencies. The module was expected to contain an assembly manifest.
at Hearthstone_Deck_Tracker.Utility.HotKeys.HotKeyManager…cctor()
— End of inner exception stack trace —
at Hearthstone_Deck_Tracker.Utility.HotKeys.HotKeyManager…ctor()
— End of inner exception stack trace —
at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
at Hearthstone_Deck_Tracker.Windows.MainWindow.InitializeComponent() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Windows\MainWindow.xaml:line 1
at Hearthstone_Deck_Tracker.Windows.MainWindow…ctor() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Windows\MainWindow.xaml.cs:line 194
at Hearthstone_Deck_Tracker.Core.d__45.MoveNext() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Core.cs:line 97
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.b__6_0(Object state)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
[Crash report 1832019-941.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2976958/Crash.report.1832019-941.txt)

Думал дело в фрейморке, но вроде нет..
![hhs](https://user-images.githubusercontent.com/48670072/54516068-88ac5d00-4966-11e9-881f-a1d99f7971e9.png)

Еще один момент, при попытке установить HDT инсталлер крашится
[SquirrelSetup.log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2976986/SquirrelSetup.log)

**Comment by riQQ** [comment]
This looks like your .NET Framework installation is broken. Try to repair it.
