### ISSUE TITLE
App crashes when I try to run it

### ISSUE THREAD

**Issue by antaresvalex** [HearthSim/Hearthstone-Deck-Tracker#3904]
I was trying to open the deck tracker after I downloaded the .exe file and ran the install. The app shows up on my screen and in my app list, so it's on my computer. 
Whenever I try to run it, I get the loading icon next to my mouse for a few seconds then it stops and nothing happens. I searched my files and it looks like the app is crashing when I try to open it. I have app crash reports from each time I've tried to open it. 
I've tried installing the .NET framework, disabling my firewall, and specifically adding the app to the list of apps that are allowed through my firewall and nothing has worked. I've uninstalled and reinstalled the software after each of these attempts and I'm not sure what else I can do to try to get the tracker to run.

**Comment by riQQ** [comment]
Please post the app crash reports.

**Comment by antaresvalex** [comment]
![Screenshot (575)](https://user-images.githubusercontent.com/50151514/56997248-2c4b7880-6b75-11e9-9e7a-6a245effca21.png)

![Screenshot (576)](https://user-images.githubusercontent.com/50151514/56997252-2f466900-6b75-11e9-9528-9387cab56a7a.png)

![Screenshot (577)](https://user-images.githubusercontent.com/50151514/56997258-33728680-6b75-11e9-8e72-5bea490a67f9.png)

**Comment by antaresvalex** [comment]
That's all it shows when I click through the app crash file but I get a new one each time I try to open the deck tracker

**Comment by riQQ** [comment]
Please follow this: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#windows

**Comment by antaresvalex** [comment]
Log Name:      Application
Source:        .NET Runtime
Date:          4/29/2019 10:17:44 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-3QM801G
Description:
Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare)
   at MS.Internal.AppModel.SiteOfOriginPart.HandleFileSource(Boolean)
   at MS.Internal.AppModel.SiteOfOriginPart.GetStreamAndSetContentType(Boolean)
   at MS.Internal.AppModel.SiteOfOriginPart.GetStreamCore(System.IO.FileMode, System.IO.FileAccess)
   at System.IO.Packaging.PackagePart.GetStream(System.IO.FileMode, System.IO.FileAccess)
   at System.IO.Packaging.PackWebResponse+CachedResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.get_ContentType()
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCacheOption, System.Guid ByRef, Boolean ByRef, System.IO.Stream ByRef, System.IO.UnmanagedMemoryStream ByRef, Microsoft.Win32.SafeHandles.SafeFileHandle ByRef)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(System.Uri, System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Net.Cache.RequestCachePolicy, Boolean)
   at System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(System.Uri, System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Net.Cache.RequestCachePolicy)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext, System.Globalization.CultureInfo, System.Object)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateObjectWithTypeConverter(MS.Internal.Xaml.ServiceProviderContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateFromValue(MS.Internal.Xaml.ServiceProviderContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object, System.Xaml.XamlMember)
   at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.CreateFromValue(MS.Internal.Xaml.ServiceProviderContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object, System.Xaml.XamlMember)
   at System.Xaml.XamlObjectWriter.Logic_CreateFromValue(MS.Internal.Xaml.Context.ObjectWriterContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object, System.Xaml.XamlMember, System.String, MS.Internal.Xaml.Runtime.IAddLineInfo)

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadComponent(System.Object, System.Uri)
   at Hearthstone_Deck_Tracker.App.InitializeComponent()
   at Hearthstone_Deck_Tracker.App.Main()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-04-30T02:17:44.026287900Z" />
    <EventRecordID>48014</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-3QM801G</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare)
   at MS.Internal.AppModel.SiteOfOriginPart.HandleFileSource(Boolean)
   at MS.Internal.AppModel.SiteOfOriginPart.GetStreamAndSetContentType(Boolean)
   at MS.Internal.AppModel.SiteOfOriginPart.GetStreamCore(System.IO.FileMode, System.IO.FileAccess)
   at System.IO.Packaging.PackagePart.GetStream(System.IO.FileMode, System.IO.FileAccess)
   at System.IO.Packaging.PackWebResponse+CachedResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.get_ContentType()
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCacheOption, System.Guid ByRef, Boolean ByRef, System.IO.Stream ByRef, System.IO.UnmanagedMemoryStream ByRef, Microsoft.Win32.SafeHandles.SafeFileHandle ByRef)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(System.Uri, System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Net.Cache.RequestCachePolicy, Boolean)
   at System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(System.Uri, System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Net.Cache.RequestCachePolicy)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext, System.Globalization.CultureInfo, System.Object)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateObjectWithTypeConverter(MS.Internal.Xaml.ServiceProviderContext, System.Xaml.Schema.XamlValueConverter`1&lt;System.ComponentModel.TypeConverter&gt;, System.Object)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateFromValue(MS.Internal.Xaml.ServiceProviderContext, System.Xaml.Schema.XamlValueConverter`1&lt;System.ComponentModel.TypeConverter&gt;, System.Object, System.Xaml.XamlMember)
   at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.CreateFromValue(MS.Internal.Xaml.ServiceProviderContext, System.Xaml.Schema.XamlValueConverter`1&lt;System.ComponentModel.TypeConverter&gt;, System.Object, System.Xaml.XamlMember)
   at System.Xaml.XamlObjectWriter.Logic_CreateFromValue(MS.Internal.Xaml.Context.ObjectWriterContext, System.Xaml.Schema.XamlValueConverter`1&lt;System.ComponentModel.TypeConverter&gt;, System.Object, System.Xaml.XamlMember, System.String, MS.Internal.Xaml.Runtime.IAddLineInfo)

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadComponent(System.Object, System.Uri)
   at Hearthstone_Deck_Tracker.App.InitializeComponent()
   at Hearthstone_Deck_Tracker.App.Main()

</Data>
  </EventData>
</Event>

**Comment by riQQ** [comment]
Does using the zipped version from https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases work: Hearthstone.Deck.Tracker-v1.8.7.zip?

**Comment by antaresvalex** [comment]
I downloaded the zipped version and extracted the files to try to run the .exe file and I got the same crash report.

**Comment by riQQ** [comment]
To which location did you extract it to? Are there any special characters in the path?

**Comment by antaresvalex** [comment]
I extracted it to my desktop folder. I'm not sure what the path is to look for special characters. I'm not great at in-depth computer stuff.

**Comment by riQQ** [comment]
Can you try another location. F.e. right below your C: drive? The path to your desktop is C:\Users\<windows username>\Desktop. So does your Windows user name contain spaces or any special chars?
