### ISSUE TITLE
It takes me longer and longer time to launch HDT.

### ISSUE THREAD

**Issue by EJoYLiBeRtY** [HearthSim/Hearthstone-Deck-Tracker#3908]
It seems like it took me longer time to launch HDT after every update.
At beginning, it took only 5 secs to launch.
But now, it would take me for nearly 2 mins, despite I'm using a SSD that needs only 5 secs to launch Hearthstone itself.
I never installed any plugins, and only have about 300 match histories and 30 decks.

**Comment by riQQ** [comment]
Does it get better when you rename the folder `%AppData%\HearthstoneDeckTracker`? You can rename it back after testing to get your settings / stats back again.

**Comment by EJoYLiBeRtY** [comment]
No, it didn't work.

**Comment by riQQ** [comment]
So it's not the data. 
Can you post a log file https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt

**Comment by EJoYLiBeRtY** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/3169667/hdt_log.txt)

**Comment by riQQ** [comment]
```
10:49:12 AM|Info|Core.Initialize >> HDT: 1.8.7.3821, Operating System: Windows 10 Home China 17134, .NET Framework: 461808
10:49:12 AM|Info|Updater.StartupUpdateCheck >> Checking for updates
10:49:12 AM|Info|Updater.GetReleaseUrl >> Downloading releases file
10:49:13 AM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
10:50:53 AM|Error|Updater.StartupUpdateCheck >> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<GitHubUpdateManager>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.Utility.Updating.Updater.<GetUpdateManager>d__10.MoveNext() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Utility\Updating\Updater.Squirrel.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.Utility.Updating.Updater.<StartupUpdateCheck>d__11.MoveNext() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Utility\Updating\Updater.Squirrel.cs:line 95
10:50:53 AM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
```

So it's the update mechanism. Is your computer connected to the internet when starting HDT?

**Comment by riQQ** [comment]
I see that you are using a chinese windows. Normally, HDT does detect chinese users by their locale zh-CN and uses another download location for these users. Are you using a different locale on your computer?

**Comment by EJoYLiBeRtY** [comment]
My system locale is China.

I'm using some proxy software to avoid China's Great Fire Wall, but turning it off changing nothing.
It took me for 110 sec to see HDT appear on my task bar. **And if I turn off the auto update, the problem will gone.**
BTW, my HDT's auto update can only tell me new version have been pushed, it always lost connection when updating. So I always upload by downloading new install packs manually...

**Comment by EJoYLiBeRtY** [comment]
Adding HDT to firewall's white list made no change.

But I noticed that, if I turn my proxy's working mode from "Proxy Auto-Config"(only using proxy on the blocked site) to "All"(using proxy on all sites), the waiting time will reduce to 5 secs.

So I think that HDT chose a wrong download location for me.

**Comment by riQQ** [comment]
What's the result of running `Get-Culture` in Powershell?

**Comment by EJoYLiBeRtY** [comment]
LCID             Name             DisplayName
----             ----             -----------
2052             zh-CN            中文(简体，中国) 【=Chinese(Simplified, China)】

**Comment by sgkoishi** [comment]
Manually add `github.com` to your PAC list might solve the problem.

**Comment by chucklu** [comment]
@EJoYLiBeRtY  Try to run the cmd  as Administrator, and execute `chcp 936`.

**Comment by chucklu** [comment]
13.250.168.23 is not in China, it's in Singapore.

11:29:17 PM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
11:29:19 PM|Error|Updater.StartupUpdateCheck >> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 13.250.168.23:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<GitHubUpdateManager>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.Utility.Updating.Updater.<GetUpdateManager>d__10.MoveNext() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Utility\Updating\Updater.Squirrel.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.Utility.Updating.Updater.<StartupUpdateCheck>d__11.MoveNext() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Utility\Updating\Updater.Squirrel.cs:line 95

**Comment by beheh** [comment]
We improved a lot here in the past few months, such as no longer blocking on updates and parsing the list of decks much faster.
