### ISSUE TITLE
Game crashing/freezing after games/ exiting

### ISSUE THREAD

**Issue by sgtslick** [HearthSim/Hearthstone-Deck-Tracker#3941]
## Bug report
Freezing quite often whenever i exit hearthstone or alt-tab, and sometimes just between single games. 

Here is the end of the log
 9:30:25 PM|Info|GameEventHandler.HandleInMenu >> Game is now in menu.
9:30:25 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
9:30:27 PM|Info|GameEventHandler.SaveAndUpdateStats >> Saving DeckStats
9:30:38 PM|Info|DeckList.ActiveDeck >> Set active deck to: 
9:30:39 PM|Info|MainWindow.ArchiveDeck >> Successfully archived deck: Arena 31-07 20:09
9:30:39 PM|Warning|Core.Reset >> Reset already in progress.
9:31:13 PM|Info|Core.UpdateOverlayAsync >> Exited game
9:31:13 PM|Info|Core.UpdateOverlayAsync >> Reset region
9:31:13 PM|Warning|Core.Reset >> Reset already in progress.
9:31:13 PM|Info|OverlayWindow.SetTopmost >> Hearthstone window not found
9:31:15 PM|Info|GameV2.Reset >> -------- Reset ---------
9:31:17 PM|Info|LogWatcherManager.Start >> Using Hearthstone log directory 'C:\Program Files (x86)\Hearthstone\Logs'
9:31:17 PM|Info|FullScreenFxHandler.Handle >> Now in queue (7/31/2019 9:30:35 PM)
9:31:17 PM|Info|FullScreenFxHandler.Handle >> Now in queue (7/31/2019 9:30:42 PM)
9:32:33 PM|Info|MainWindow.Window_Closing >> Shutting down...

It also eats up huge chunk of CPU over 30% which is a lot, hearthstone itself only uses like 10%. 
### Log/Screenshots

![Decktracker crash](https://user-images.githubusercontent.com/9771207/62209170-2f583e00-b3dc-11e9-88cd-1e1b93817b69.png)

**Comment by riQQ** [comment]
What does this have to do with crashes? I don't see any hints at crashes.

**Comment by sgtslick** [comment]
It says (not responding) in task manager. As in, it froze/crashed. This happens quite frequently.

**Comment by riQQ** [comment]
Okay, so it's not a crash. A crash is if the process is exited abruptly. It's a hang / freeze.

Please create a minidump on the hang and upload it here or on a file hoster if it's to big for Github: https://support.microsoft.com/en-us/help/931673/how-to-create-a-user-mode-process-dump-file-in-windows

**Comment by wshuts** [comment]
I am experiencing the same behavior occasionally when exiting hearthstone and/or battle.net.
I was able to run hearthstone in debug mode using visual studio.
When the behavior occurred, I paused the debugger to capture the stack.

<img width="1280" alt="hdt-debug" src="https://user-images.githubusercontent.com/56050015/221431507-d0484e60-5785-426d-8ecd-94a6cb193254.png">

Following the "breadcrumbs":
HearthWatcher
QueueWatcher
CheckForQueue
FindGameState

The debugger paused at the "getter" call for that property.

It's only one observation - but - I hope it helps.
Perhaps some try/catch/exception handling could be added.

**Comment by wshuts** [comment]
More info:
2:36:02 PM|Warning|Core.Initialize >> HearthMirror Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object , String )
   at HearthMirror.Reflection.GetService(String name)
   at HearthMirror.Reflection.<>c.<GetFindGameState>b__123_0()
   at HearthMirror.Reflection.TryGetInternal[T](Func`1 action, Boolean clearCache)
