### ISSUE TITLE
Crash on export with latest version

### ISSUE THREAD

**Issue by anonymous555** [HearthSim/Hearthstone-Deck-Tracker#4013]
On the export menu, I now always get Error: object reference not set to an instance of an Object.

**Comment by anonymous555** [comment]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.Hearthstone.Collection..ctor(UInt64 accountHi, UInt64 accountLo, BattleTag battleTag, Collection collection) in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Hearthstone\Collection.cs:line 13
   at Hearthstone_Deck_Tracker.Hearthstone.CollectionHelper.<UpdateCollection>d__9.MoveNext() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Hearthstone\CollectionHelper.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.Hearthstone.CollectionHelper.<GetCollection>d__6.MoveNext() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Hearthstone\CollectionHelper.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.FlyoutControls.DeckExport.DeckExportViewModel.<UpdateMissingCards>d__17.MoveNext() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\FlyoutControls\DeckExport\DeckExportViewModel.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by anonymous555** [comment]
Fixed itself somehow
