### ISSUE TITLE
Ranked data lost when app is updated

### ISSUE THREAD

**Issue by pho3bus** [HearthSim/Hearthstone-Deck-Tracker#4081]
### Expected Behavior
HDT should retain rank data between updates.

### Actual Behavior
The past two times HDT has updated on my PC, the "Rank" data is lost (Diamond 5, etc. in the Constructed/Matches display). The last occurrence was with the 5/13/2020 update. Not only is the "Rank" data display missing, but if you filter by "Ranked" in the "Mode" drop-down in Constructed/Matches, those matches do not show up as Ranked games. This makes it difficult to track ranked games across updates. 

### Steps to reproduce behavior
So far this has happened with the last two auto-updates.

### Log/Screenshots
hdt and SquirrelSetup logs attached for latest occurrence.
[hdt_log_1589432061.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4644719/hdt_log_1589432061.txt)
[SquirrelSetup.log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4644721/SquirrelSetup.log)
[SquirrelSetup-1.log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4644723/SquirrelSetup-1.log)
![Capture](https://user-images.githubusercontent.com/48997811/82225497-e6319600-98ea-11ea-9d1f-212bc1976748.JPG)

**Comment by azeier** [comment]
Did you start an old version of HDT at some point by any chance? The only reason I can think of for this happening is a version of HDT that doesn't have the new rank system overwriting the data, and thus deleting the new rank fields.

**Comment by pho3bus** [comment]
That's possible. Often the auto-updater for HDT doesn't seem to work for me and I'll end up one or two versions behind, so I end up downloading and reinstalling, and I feel like over time HDT has been installed to different locations on my drive. Is there a way to make sure I don't have old versions installed?  How can I find old versions and uninstall or delete them?

**Comment by riQQ** [comment]
Search for `HearthstoneDeckTracker.exe`

**Comment by pho3bus** [comment]
This happened again with yesterday's update. I've got a hearthstonedecktrack.exe in c:\users\<username>AppData\Local\HearthstoneDeckTracker and another in c:\users\<username>\AppData\Local\HearthstoneDeckTracker\app-1.12.6. Which one is the correct one (the latter I'm assuming)? There is also an update.exe file in the first path--is this the correct spot for it?

**Comment by riQQ** [comment]
Both are correct. The first one is a stub that runs the updater and the correct version afterwards. If these are the only .exe files you have, then you don't have any old versions.

Can you upload the hdt.og from yesterday?

**Comment by pho3bus** [comment]
Here are the log files
[hdt_log_1590453992.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4683545/hdt_log_1590453992.txt)
[hdt_log_1590453799.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4683546/hdt_log_1590453799.txt)
[hdt_log_1590453764.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4683547/hdt_log_1590453764.txt)
[hdt_log_1590439368.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4683548/hdt_log_1590439368.txt)
[hdt_log_1590427527.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4683549/hdt_log_1590427527.txt)




 from yesterday.

**Comment by riQQ** [comment]
From the first log, it's starting an old version:
```
7:43:17 PM|Info|Core.Initialize >> HDT: 1.3.0.3081, Operating System: Windows 10 Enterprise 18363, .NET Framework: 528040
7:43:18 PM|Info|Updater.StartupUpdateCheck >> Checking for updates
7:43:18 PM|Info|Updater.GetReleaseUrl >> Downloading releases file
7:43:18 PM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
7:43:19 PM|Error|Updater.StartupUpdateCheck >> System.Exception: Update.exe not found, not a Squirrel-installed app?
   at Squirrel.UpdateManager.getUpdateExe()
   at Squirrel.UpdateManager.getApplicationName()
   at Squirrel.UpdateManager..ctor(String urlOrPath, String applicationName, String rootDirectory, IFileDownloader urlDownloader)
   at Squirrel.UpdateManager.<GitHubUpdateManager>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.Utility.Updating.Updater.<GetUpdateManager>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.Utility.Updating.Updater.<StartupUpdateCheck>d__11.MoveNext()
7:43:19 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
```

All the other ones are the new version. Did you do something different when starting HDT at this time? There seems to be an old version somewhere that you haven't found.

**Comment by pho3bus** [comment]
I typically pin a shortcut to HDT to my Win10 taskbar for easy access. But, because HDT installs to a different directory each time a new version is released, the shortcut breaks when an update comes out. So I have to search for HDT in the Win10 search bar...this must be where it is finding old versions. At this point I have uninstalled all versions that I could find via file search and add/remove program and re-installed the latest version, so we'll see what happens when the next release comes out.

**Comment by riQQ** [comment]
You don't have to repin anymore, this was fixed some versions ago.
