### ISSUE TITLE
1.4.14 Broke API used by pack tracker plugin

### ISSUE THREAD

**Issue by anonymous555** [HearthSim/Hearthstone-Deck-Tracker#4262]
Release 1.4.14 broke the API used by plugin Pack Tracker 1.3.2
Was working fine before 1.4.14

Make sure you are using the latest version of the Plugin and HDT.

System.MissingMethodException: Method not found: 'Boolean HearthMirror.Objects.Card.get_Premium()'.
   at PackTracker.PackWatcher.NewPack(Object sender, PackEventArgs e)
   at HearthWatcher.PackOpeningWatcher.PackEventHandler.Invoke(Object sender, PackEventArgs args)
   at HearthWatcher.PackOpeningWatcher.<CheckForPacks>d__13.MoveNext() in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\HearthWatcher\PackOpeningWatcher.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by azeier** [comment]
This is a required change to support diamond cards. Please open an issue on the plugin repo.

**Comment by TheMrKochan** [comment]
> This is a required change to support diamond cards. Please open an issue on the plugin repo.

Could you show us what exactly to replace or help us adapt the plugin to the current version of HDT?

**Comment by azeier** [comment]
“HearthMirror.Objects.Card.Premium” (boolean) has been replaced with “HearthMirror.Objects.Card.PremiumType”, which is an int (enum technically) with 0 being normal, 1 being premium and 2 diamond. That should be the only change.

**Comment by TheMrKochan** [comment]
> “HearthMirror.Objects.Card.Premium” (boolean) has been replaced with “HearthMirror.Objects.Card.PremiumType”, which is an int (enum technically) with 0 being normal, 1 being golden and 2 diamond. That should be the only change.
> 
> Any required changes should be similar to this commit: [73aca3e](https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/73aca3e48fabd0f9b13336892716731373b940df)

```
System.NullReferenceException: An object reference does not point to an instance of an object.
   at PackTracker.View.Average.<>c.<AddCounts>b__22_0(Card x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PackTracker.View.Average.AddCounts(IEnumerable`1 Packs)
   at PackTracker.View.Average.History_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at PackTracker.History.OnCollectionChanged(NotifyCollectionChangedEventArgs Args)
   at PackTracker.History.<Initialize>b__8_0(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at PackTracker.Plugin.<.ctor>b__13_0(Object sender, PackOpenedEventArgs e)
   at PackTracker.PackWatcher.OnPackOpened(Pack Pack)
   at PackTracker.PackWatcher.NewPack(Object sender, PackEventArgs e)
   at HearthWatcher.PackOpeningWatcher.PackEventHandler.Invoke(Object sender, PackEventArgs args)
   at HearthWatcher.PackOpeningWatcher.<CheckForPacks>d__13.MoveNext() в D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\HearthWatcher\PackOpeningWatcher.cs:line  58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Can you help with this please :(
