### ISSUE TITLE
Can't open deck tracker main window.

### ISSUE THREAD

**Issue by PowerLiam** [HearthSim/Hearthstone-Deck-Tracker#4339]
### Expected Behavior
I run Hearthstone deck tracker, click it's icon on the task bar (or press show from the system tray) and the main window pops up.

### Actual Behavior
The process starts, and the in-game overlay works, but the main window will never show.  I tried clicking "show" in the system tray and tabbing to the window, but both show nothing.

### Steps to reproduce behavior
Uninstall + reinstall the program, run the program, click show on the system tray or click on the icon in the taskbar, observe that the main window does not show.

### Log/Screenshots

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/7073037/hdt_log.txt)

The 3 errors I see:
1.
2:30:52 PM|Warning|Core.Initialize >> HearthMirror Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object , String )
   at HearthMirror.Reflection.GetService(String name)
   at HearthMirror.Reflection.InternalGetGameType()
   at HearthMirror.Reflection.TryGetInternal[T](Func`1 action, Boolean clearCache)
   
2.
2:30:53 PM|Warning|Core.Initialize >> HearthMirror Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CallSite.Target(Closure , CallSite , Object , String )
   at HearthMirror.Reflection.GetService(String name)
   at HearthMirror.Reflection.InternalGetGameType()
   at HearthMirror.Reflection.TryGetInternal[T](Func`1 action, Boolean clearCache)
   
3.   
2:30:53 PM|Warning|Core.Initialize >> HearthMirror Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at HearthMirror.ProcessView.GetExport(String name)
   at HearthMirror.Mirror.get_Root()
   at HearthMirror.Reflection.GetService(String name)
   at HearthMirror.Reflection.InternalGetGameType()
   at HearthMirror.Reflection.TryGetInternal[T](Func`1 action, Boolean clearCache)
   
Looks like the various overlay components function properly, but the "core initialize" is repeatedly going wrong.

**Comment by W8988487** [comment]
1.Uninstall HDT.
2.Delete the unzipped folder and the app data folder (C:\Users"username"\AppData\Roaming\HearthstoneDeckTracker).
3.Reinstall HDT.
Hope it works.
