### ISSUE TITLE
Can't load Boonwins battlegrounds Tracker

### ISSUE THREAD

**Issue by Tyler420HS** [HearthSim/Hearthstone-Deck-Tracker#4352]
My HDT opens but won't load Boonwins battlegrounds tracker, I get an error.

I realized this happened when I attempted to set a background image for the battlegrounds tracker.

I've tried reinstalling HDT, boonwins tracker and even restarting my pc but I still get this error where it's trying to load the wallpaper image I attempted to set earlier.
I'm not sure why even after reinstalling its still trying to show the wallpaper, I even deleted that wallpaper off my pc.

I really was enjoying using this plugin and really want to be able to use it again. 
Please help!

Log:
System.IO.FileNotFoundException: Could not find file 'C:\Users\xgodl\AppData\Roaming\HearthstoneDeckTracker\Plugins\BoonwinsBattlegroundTracker\Img\teahub.io-khal-drogo-wallpaper-1784189.png'.
File name: 'C:\Users\xgodl\AppData\Roaming\HearthstoneDeckTracker\Plugins\BoonwinsBattlegroundTracker\Img\teahub.io-khal-drogo-wallpaper-1784189.png'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource)
   at BoonwinsBattlegroundTracker.BgMatchOverlay.SetBackground(Uri fileName)
   at BoonwinsBattlegroundTracker.BgMatchOverlay.SetImgPathes()
   at BoonwinsBattlegroundTracker.BgMatchOverlay..ctor()
   at BoonwinsBattlegroundTracker.BgMatchDataPlugin.OnLoad()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load() in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Plugins\PluginWrapper.cs:line 93

**Comment by ceceita** [comment]
im not expert or good code reader and programer , but this seems to be a plugin related problem not under hdt 
so https://github.com/boonwin/BoonwinsBattlegroundsTracker
but from log seems it still know where to search for your background that means there are still some configs files around ( not in hdt folder since you deleted them ) pointing to it that cause the problem
on the plugin repo i found this
https://github.com/boonwin/BoonwinsBattlegroundsTracker/blob/master/BoonwinsBattlegroundTracker/Config/FilePathes.cs
seems like it saves to some \boonwin\data\  folder .. 
as i said i dont know half of what is writed there , but in you case i will try to search for that specific folder , make a bakup  , and delete ...
