### ISSUE TITLE
CPU usage drops to 3% when I HDT running

### ISSUE THREAD

**Issue by ricencracker** [HearthSim/Hearthstone-Deck-Tracker#4359]
## Bug report
After the last Hearthstone update my CPU usage drops to 3% from around 20% when I have HDT running and I try to do anything in Hearthstone

### Expected Behavior
Work normally

### Actual Behavior
game is choppy and unplayable with HDT running

### Steps to reproduce behavior
Just running HDT with Hearthstone causes it to happen

### Log/Screenshots
9:02:50 PM|Info|Core.Initialize >> HDT: 1.16.7.5661, Operating System: Windows 10 Enterprise 19042, .NET Framework: 528372
9:02:50 PM|Info|Updater.StartupUpdateCheck >> Checking for updates
9:02:50 PM|Info|Updater.GetReleaseUrl >> Downloading releases file
9:02:50 PM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
9:02:51 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
9:02:51 PM|Info|Updater.SquirrelUpdate >> No new updated available
9:02:52 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
9:02:52 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
9:02:52 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
9:02:52 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
9:02:52 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
9:02:52 PM|Info|GameV2.Reset >> -------- Reset ---------
9:02:55 PM|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
9:02:55 PM|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
9:02:55 PM|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
9:02:55 PM|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
9:02:55 PM|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
9:02:55 PM|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_037
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_035
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_026
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_027
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_039
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_037
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_022
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_035
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_039
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_037
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_035
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_037
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_035
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_037
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_027
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_030
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_035
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_030
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_037
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_035
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_034
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_038
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_037
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_033
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_015
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_039
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_035
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_038
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_039
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_022
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_027
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_035
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_014
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_013
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_025
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_024
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_037
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_028
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_035
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_039
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_022
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_039
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_022
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_039
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_022
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_037
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_027
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_039
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_030
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_035
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_014
9:02:56 PM|... 3 duplicate messages
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_027
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_037
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_035
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_039
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_036
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_037
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_035
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_014
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_037
9:02:56 PM|Warning|Database.GetCardFromId >> Could not find card with ID=WE1_033
9:02:56 PM|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
9:02:56 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
9:03:04 PM|Info|GameV2.Reset >> -------- Reset ---------
9:03:06 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
9:03:06 PM|Info|BackupManager.Run >> Running BackupManager
9:03:06 PM|Info|BackupManager.Run >> Backup for today already exists
9:03:06 PM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
9:03:07 PM|Error|PluginManager.GetModule >> Error loading C:\Users\joshua\AppData\Local\HearthstoneDeckTracker\app-1.16.7\Plugins\ArenaHelper\ArenaHelper.dll:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Hearthstone_Deck_Tracker.Plugins.PluginManager.GetModule(String pFileName, Type pTypeInterface) in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Plugins\PluginManager.cs:line 196
9:03:07 PM|Info|Helper.GetCurrentRegion >> Region: US
9:03:07 PM|Info|BackupManager.Run >> Running BackupManager
9:03:07 PM|Info|BackupManager.Run >> Backup for today already exists
9:03:07 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
9:03:07 PM|Info|LogWatcherManager.Start >> Using Hearthstone log directory 'C:\Program Files (x86)\Hearthstone\Logs'
9:03:07 PM|Info|LogWatcherManager.OnLogFileFound >> LoadingScreen
9:03:07 PM|Info|LogWatcherManager.OnLogFileFound >> FullScreenFX
9:03:07 PM|Info|LogWatcherManager.OnLogFileFound >> Achievements
9:03:07 PM|Info|HSReplayNetOAuth.UpdateAccountData >> Updating account data...
9:03:07 PM|Info|HsReplayDecks.Load >> Loaded from disk: Count=1278, ServerTS=11/8/2021 8:12:20 PM, Downloaded=11/8/2021 8:52:39 PM Age=00:10:28.0612680
9:03:07 PM|Info|HsReplayDecks.Load >> Complete: Count=1278, ServerTS=11/8/2021 8:12:20 PM, Downloaded=11/8/2021 8:52:39 PM Age=00:10:28.0612680
9:03:07 PM|Info|GameV2.CurrentMode >> LOGIN
9:03:07 PM|Info|GameV2.CurrentMode >> HUB
9:03:07 PM|Info|GameV2.CurrentMode >> BACON
9:03:08 PM|Info|HSReplayNetOAuth.UpdateAccountData >> Found account: ThatGuyThere#1117
9:03:08 PM|Info|HSReplayNetOAuth.UpdateTwitchUsers >> Fetching twitch accounts...
9:03:08 PM|Info|HSReplayNetOAuth.UpdateTwitchUsers >> Saved 1 account(s): thatotherjosh
9:03:40 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
9:04:42 PM|Info|Help.Hyperlink_RequestNavigate >> [Helper.TryOpenUrl] https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues
9:12:29 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
9:14:11 PM|... 1 duplicate messages
9:14:11 PM|Info|MainWindow.Window_Closing >> Shutting down...
9:14:11 PM|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates

**Comment by alexbereznikov** [comment]
Can confirm, started happening to me a while ago (3-4 weeks) too. Hearthstone instantly becomes unplayable right when HDT is started, and everything is ok right after HDT is closed. There is an answer in FAQ about that (related to Windows Aero), but:
* I have no idea how to enable Windows Aero in Windows 11
* Everything was working flawlessly with the same setup about a month ago, there were no hardware or software changes

**Comment by truckerpatrick** [comment]
I've been experiencing this exact same thing. No clue how to fix it I've tried changing almost every setting in the tracker menu and even figured out how to enable Windows Aero just to find that it fixed absolutely nothing:(
