### ISSUE TITLE
Crash in log reader

### ISSUE THREAD

**Issue by funklessmann** [HearthSim/Hearthstone-Deck-Tracker#4496]
### Expected Behavior

Deck tracker runs
### Actual Behavior

Deck tracker crashes in nearly every game
### Steps to reproduce behavior

Play a game, deck tracker crashes, nearly every game. Wild, standard, battlegrounds, solo - constant crashes. 
### Log/Screenshots

I can see the "Crash Log" window in my task bar, clicking it brings up nothing, the crash log itself has crashed(!)

[image](https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/126020556/d51e0ba3-4151-441e-aa92-15f994a1baf0)

System info:

ROG Zephyrus M16 GU60 3ZW
Processor 12th Gen Intel(R) Core(TM) i9-12900H   2.50 GHz
Installed RAM 40.0 GB (39.7 GB usable)
System type 64-bit operating system, x64-based processor
Edition Windows 11 Home
Version 22H2
Installed on ‎3/‎16/‎2023
OS build 22621.2283
Experience Windows Feature Experience Pack 1000.22662.1000.0

**Comment by joolean** [comment]
Hi! Thanks for the report. It would help us debug if you could attach both an HDT log file and any HDT crash log you can find. Here are instructions for doing that: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by xironfs** [comment]
I have the same problem  System.IO.FileNotFoundException: Could not load file or assembly 'untapped-scry-dotnet.dll' or one of its dependencies. Не найден указанный модуль.
Имя файла: 'untapped-scry-dotnet.dll'
   в HearthMirror.Status.GetStatus()
   в Hearthstone_Deck_Tracker.LogReader.Handlers.LoadingScreenHandler.<CheckMirrorStatus>d__8.MoveNext() в D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\LogReader\Handlers\LoadingScreenHandler.cs:строка 187
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by joolean** [comment]
@xironfs Thank you! Is there any information below the stack trace? It might start with `=== Pre-bind state information ===`

**Comment by funklessmann** [comment]
### HDT Log files:

[hdt_log_1695939388.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/12754753/hdt_log_1695939388.txt)
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/12754754/hdt_log.txt)

### HDT crash logs

None in either of the version folders in HDT install folder

### Windows Log Files:

Log Name:      Application
Source:        .NET Runtime
Date:          9/26/2023 7:54:40 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ROGZephyrusGU60
Description:
Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Media.MediaContext.LeaveInterlockedPresentation()
   at System.Windows.Media.MediaContext.RemoveChannels()
   at System.Windows.Media.MediaContext.Dispose()
   at System.Windows.Media.MediaContext.OnDestroyContext(System.Object, System.EventArgs)
   at System.EventHandler.Invoke(System.Object, System.EventArgs)
   at System.Windows.Threading.Dispatcher.ShutdownImplInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.Dispatcher.ShutdownImpl()
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Hearthstone_Deck_Tracker.App.Main()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-09-26T23:54:40.9096539Z" />
    <EventRecordID>36222</EventRecordID>
    <Correlation />
    <Execution ProcessID="9388" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>ROGZephyrusGU60</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Media.MediaContext.LeaveInterlockedPresentation()
   at System.Windows.Media.MediaContext.RemoveChannels()
   at System.Windows.Media.MediaContext.Dispose()
   at System.Windows.Media.MediaContext.OnDestroyContext(System.Object, System.EventArgs)
   at System.EventHandler.Invoke(System.Object, System.EventArgs)
   at System.Windows.Threading.Dispatcher.ShutdownImplInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.Dispatcher.ShutdownImpl()
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Hearthstone_Deck_Tracker.App.Main()

</Data>
  </EventData>
</Event>

### Setup log files

## SquirrelTemp

[SquirrelSetup.log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/12754767/SquirrelSetup.log)

## HDT Directory

[SquirrelSetup.log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/12754769/SquirrelSetup.log)

**Comment by funklessmann** [comment]
Another Windows error from a few days ago here: 

Log Name:      Application
Source:        .NET Runtime
Date:          9/24/2023 9:05:59 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ROGZephyrusGU60
Description:
Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare)
   at HearthWatcher.LogReader.LogFileWatcher.ReadLogFile()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-09-25T01:05:59.1211335Z" />
    <EventRecordID>35585</EventRecordID>
    <Correlation />
    <Execution ProcessID="25016" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>ROGZephyrusGU60</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare)
   at HearthWatcher.LogReader.LogFileWatcher.ReadLogFile()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

</Data>
  </EventData>
</Event>

And a different previous log: 
[hdt_log_1695906403.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/12754818/hdt_log_1695906403.txt)

**Comment by beheh** [comment]
I think the original bug is fixed, and the last crash log is the same as #4559.
