### ISSUE TITLE
[Battlegrounds] Win games are not recording to last games

### ISSUE THREAD

**Issue by ShBNK** [HearthSim/Hearthstone-Deck-Tracker#4528]
### Expected Behavior

Version: 1.23.15
I won my last game with Sire Denathrius, so I expected it would appear on stats

### Actual Behavior

I see only my previous game with Tess Graymane
![hearth](https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/5736607/95cfa5f6-55b6-40d0-a8ad-b37aea88971c)
![hdt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/5736607/234ccd88-1e42-4803-a5c3-cd3fb812690f)

### Log/Screenshots

In my last 2 winning game I found the same logs part:

12:20:31 AM|Info|GameEventHandler.HandleGameEnd >> Game ended...
12:20:31 AM|Info|GameEventHandler.HandleGameEnd >> Format: 
12:20:31 AM|Info|GameStats.GameEnd >> Current Game ended after 18 turns
12:20:31 AM|Info|GameEventHandler.HandleGameEnd >> Assigned current deck to default BaconPHhero deck.
12:20:32 AM|Error|GameEventHandler.HandleGameEnd >> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.Join(String separator, String[] value, Int32 startIndex, Int32 count)
   at System.String.Join(String separator, String[] value)
   at Hearthstone_Deck_Tracker.HsReplay.LogUploader.<Upload>d__1.MoveNext() in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\HsReplay\LogUploader.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Hearthstone_Deck_Tracker.GameEventHandler.<SaveReplays>d__16.MoveNext() in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\GameEventHandler.cs:line 189
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Hearthstone_Deck_Tracker.GameEventHandler.<HandleGameEnd>d__48.MoveNext() in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\GameEventHandler.cs:line 819
12:20:32 AM|Info|BobsBuddyInvoker.ValidateSimulationResultAsync >> result=Win, lethalResult=NoOneDied
12:20:37 AM|Info|GameV2.CurrentMode >> BACON
12:20:37 AM|Info|GameEventHandler.HandleInMenu >> Game is now in menu.
12:20:37 AM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
12:20:37 AM|Info|GameEventHandler.SaveAndUpdateStats >> Gamemode Battlegrounds is not supposed to be saved. Removed game from default BaconPHhero.
12:20:41 AM|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates

**Comment by beheh** [comment]
Fixed in the upcoming HDT version (v1.25.2).
