### ISSUE TITLE
Potential memory leak in version 1.29.0.6757 leading to silent crash.

### ISSUE THREAD

**Issue by jamiemoles** [HearthSim/Hearthstone-Deck-Tracker#4557]
### Expected Behavior

Program to function normally.

### Actual Behavior

Program is terminating saliently in the background with no error messages.   Windows Event Viewer has two entries - one for the .NET runtime, event id 1026 and one for HearthstoneDeckTracker.exe event id 1000.  

### Steps to reproduce behavior

Problem seems to be with Battlegrounds.   Run deck tracker, play battlegrounds, notice at some point no hud is present.  Deck tracker icon is present in icon tray but non-responsive.

### Log/Screenshots

Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Media.MediaContext.LeaveInterlockedPresentation()
   at System.Windows.Media.MediaContext.RemoveChannels()
   at System.Windows.Media.MediaContext.Dispose()
   at System.Windows.Media.MediaContext.OnDestroyContext(System.Object, System.EventArgs)
   at System.EventHandler.Invoke(System.Object, System.EventArgs)
   at System.Windows.Threading.Dispatcher.ShutdownImplInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.Dispatcher.ShutdownImpl()
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Hearthstone_Deck_Tracker.App.Main()
   
================================   

   
Faulting application name: HearthstoneDeckTracker.exe, version: 1.29.0.6757, time stamp: 0xa04b832f
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4412, time stamp: 0x6d8c3da8
Exception code: 0xe0434352
Fault offset: 0x00140b82
Faulting process ID: 0xcbfc
Faulting application start time: 0x01dab8d9029cc0a2
Faulting application path: C:\Users\Jamie\AppData\Local\HearthstoneDeckTracker\app-1.29.0\HearthstoneDeckTracker.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: 95cfc2dd-8706-4c62-aff6-5c3b9e0ca11f
Faulting package full name: 
Faulting package-relative application ID:

**Comment by beheh** [comment]
Hey, thanks for the report! After how many games are seeing this?

**Comment by jamiemoles** [comment]
I can't be certain, but it's not a super low number.  I will monitor play today and see if I can get you a number.

**Comment by beheh** [comment]
@jamiemoles For further debugging, could you please upload your entire HDT config folder? You'll find it at `C:\Users\<username>\AppData\Roaming\HearthstoneDeckTracker`

**Comment by jamiemoles** [comment]
Yes.  it's 300+ MB so I'll upload to Onedrive and drop you a link here.

**Comment by jamiemoles** [comment]
Give it 10 mins to upload, then you can access here:  https://1drv.ms/u/s!AnXPiqttHvQ9hfZ59gUOxTqGYRQGxQ?e=FOq1zK

**Comment by beheh** [comment]
Great, thanks. You can delete the file again. We'll continue investigating.

**Comment by beheh** [comment]
We've been able to identify a memory leak happening in the minion browser and are trying to locate it further.

**Comment by jamiemoles** [comment]
Nice.  Just to add some more validation,  I've tried this on another machine and seen the same issue.

**Comment by beheh** [comment]
@jamiemoles Could you try [this build](https://drive.google.com/file/d/1cduiJuJtg1Vz5eT3MqYSZ7d19_GSDOJA/view?usp=drive_link) and see if it's any better? Just unpack the Zip and run the executable (it's not signed though, so you'll likely get a warning from Windows).

**Comment by jamiemoles** [comment]
Running now.   I'll let you know if I see any issues.
________________________________

**Comment by beheh** [comment]
Closing, if this happens again please let me know here.
