### ISSUE TITLE
IOException and silent crash in LogReader

### ISSUE THREAD

**Issue by bstook** [HearthSim/Hearthstone-Deck-Tracker#4559]
### Expected Behavior

Program to not crash and especially without a notification.

### Actual Behavior

HearthstoneDeckTracker.exe is terminating at seemingly random times after playing at least one game of Standard. This has been happening for quite a few versions and has persisted through a reformat and reinstall of Windows on my end.

### Steps to reproduce behavior

It seems to happen more often than not and when it does, it's always after Heathstone has been launched at least once.

### Log/Screenshots

Faulting application name: HearthstoneDeckTracker.exe, version: 1.29.3.6777, time stamp: 0xf532b016
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3733, time stamp: 0xf527a1c6
Exception code: 0xe0434352
Fault offset: 0x00149a72
Faulting process id: 0x0x3FCC
Faulting application start time: 0x0x1DAC3D6E575F319
Faulting application path: C:\Users\mr.\AppData\Local\HearthstoneDeckTracker\app-1.29.3\HearthstoneDeckTracker.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: dc76415f-d4b9-4afc-bf34-53c76e440cd0
Faulting package full name: 
Faulting package-relative application ID: 

---------------------

Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare)
   at HearthWatcher.LogReader.LogFileWatcher.ReadLogFile()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by beheh** [comment]
Hi there, thanks for the report! We'll have a fix for that in the next HDT version.
