### ISSUE TITLE
HDT crashes constantly - OOM

### ISSUE THREAD

**Issue by hrosental** [HearthSim/Hearthstone-Deck-Tracker#4560]
### Expected Behavior

HDT works without issue

### Actual Behavior

HDT crashes everytime after starting a new game. It takes about 5 to 6 rounds and the game crashes with a OOM. See crash report folder for stack

### Steps to reproduce behavior

Just start HDT and a new game. Issue happens all the time on my system, windows 11 10.0.22631 x-64 on a surface laptop 6. 32GB of ram, Intel arc graphics, 128 MB with 16GB shared

### Log/Screenshots

[Crash Reports.zip](https://github.com/user-attachments/files/16178851/Crash.Reports.zip)

Example:
########## 7/10/2024 5:37:43 PM ##########
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Logfile: C:\Users\helior\AppData\Roaming\HearthstoneDeckTracker\Logs\hdt_log.txt

**Comment by beheh** [comment]
Hey there! Thanks for the report. Could you please also send us your HDT log folder (found in `C:\Users\<username>\AppData\Roaming\HearthstoneDeckTracker\Logs`)?

**Comment by hrosental** [comment]
[Logs.zip](https://github.com/user-attachments/files/16249058/Logs.zip)

File attached. Just got the latest update and issue still happening. Game is Heartstone, and I don't play anything else, so I can't tell if issue is game specific.

**Comment by hrosental** [comment]
I have captured a couple of crash dumps of the process, but can't upload as the file size exceeds the allowed 25MB. I also can't debug them as I don't have symbols for the executable and libraries. Let me know if you are interested on them and if yes, how I should send them to you.

**Comment by hrosental** [comment]
This has been outstanding for a good time. I've just installed 1.31.0 and issue still persists.

**Comment by kriki200** [comment]
You could put them on to mega and just share the link.

**Comment by eljke** [comment]
I confirm the problem of constantly crashing. Also attached the log.
It seems that it can only be reproduced on Intel Arc graphics.
Game type doesn't matter (Heartstone, Battlegrounds, Tavern Brawl, etc.).
[hdt_log.txt](https://github.com/user-attachments/files/17269000/hdt_log.txt)

**Comment by Solomon-zhao** [comment]
I confirmed the problem also, plz help and let us know how to deal with it.

**Comment by LineWolff** [comment]
I had some luck with setting vsync=0 in the ini file. Can't guarantee it was the single one thing, since I tried some different stuff, but I'm pretty sure this was the culprit.

**Comment by eljke** [comment]
> I had some luck with setting vsync=0 in the ini file. Can't guarantee it was the single one thing, since I tried some different stuff, but I'm pretty sure this was the culprit. Intel Arc onboard + Nvidia 4070 (laptop).

Excuse me, could you please tell us where is this ini file located?

**Comment by LineWolff** [comment]
> Excuse me, could you please tell us where is this ini file located?
"C:\Users\USER\AppData\Local\Blizzard\Hearthstone\options.txt"

**Comment by Winnerstedt** [comment]
I am also experiencing this issue, I would love some assistance!

**Comment by Jack251970** [comment]
Still encounter it in the latest version with Intel Arc onboard + Nvidia 4070 (laptop)

**Comment by Jack251970** [comment]
Setting vsync=0 cannot help...

**Comment by beheh** [comment]
If you're still encountering this, please try disabling the "Use Hardware Acceleration when available" setting in HDT and let us know if that fixes it.
