### ISSUE TITLE
1.36.4  broke compatibility with Hearthstone.Player.get_Class()'

### ISSUE THREAD

**Issue by anonymous555** [HearthSim/Hearthstone-Deck-Tracker#4592]
### Expected Behavior

This broke a prior plugin (Advisor).  Everything was working fine before this release.  Looks like you change the deck tracker API.  Unfortunately, the plugin is no longer maintained, so an update on their end doesn't look likely.  Can you restore API compatibility please?

System.MissingMethodException: Method not found: 'System.String Hearthstone_Deck_Tracker.Hearthstone.Player.get_Class()'.
   at HDT.Plugins.Advisor.Advisor.<UpdateCardList>d__20.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at HDT.Plugins.Advisor.Advisor.UpdateCardList()
   at HDT.Plugins.Advisor.Advisor..ctor(AdvisorOverlay overlay) in C:\Users\Jacob\Documents\Git\Advisor\Advisor\Advisor.cs:line 41
   at HDT.Plugins.Advisor.AdvisorPlugin.<OnLoad>d__14.MoveNext() in C:\Users\Jacob\Documents\Git\Advisor\Advisor\AdvisorPlugin.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Actual Behavior

This broke a prior plugin (Advisor).  Everything was working fine before this release.  Looks like you change the deck tracker API.  Unfortunately, the plugin is no longer maintained, so an update on their end doesn't look likely.  Can you restore API compatibility please?

System.MissingMethodException: Method not found: 'System.String Hearthstone_Deck_Tracker.Hearthstone.Player.get_Class()'.
   at HDT.Plugins.Advisor.Advisor.<UpdateCardList>d__20.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at HDT.Plugins.Advisor.Advisor.UpdateCardList()
   at HDT.Plugins.Advisor.Advisor..ctor(AdvisorOverlay overlay) in C:\Users\Jacob\Documents\Git\Advisor\Advisor\Advisor.cs:line 41
   at HDT.Plugins.Advisor.AdvisorPlugin.<OnLoad>d__14.MoveNext() in C:\Users\Jacob\Documents\Git\Advisor\Advisor\AdvisorPlugin.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by beheh** [comment]
Hello, this change is expected because we recently cleaned this up in 836c573c89c98e521c01523b45aae5b5e66772d4 to better differentiate between the starting player class and the current player class, instead of the arbitrary "Player.Class" that was used in ambiguous ways previously and we wanted to make sure we no longer depend on it.

For the sake of plugins I will make a change to ensure we have backwards-compatibility, but I'd like to stress that **in general plugins will have to updated by authors once in a while**. We're in phase right now where we're planning and making an unprecedented number of changes to HDT, and we cannot guarantee to always stay compatible with every existing plugin.

If a plugin has been abandoned you should probably either reach out to the author or prepare yourself to take a crack at updating it yourself.
