### ISSUE TITLE
System.OutOfMemoryException of Deck tracker while playing Battlegrounds ( Season 9 )

### ISSUE THREAD

**Issue by CheliosSk** [HearthSim/Hearthstone-Deck-Tracker#4599]
### Expected Behavior

Deck tracker should work without issues.

### Actual Behavior

While playing the HS battlegrounds, deck tracker stop working in the middle of the game. This happens by random but almost each game. I Was not able to test what cause the issue.

Application has to be shutdown and then restarted.

I have tried to reinstall the tracker but still it has the same issue. Deck tracker is without any plugins or changes.

I am playing on Windows 11 home, i9-13900H, DDR5 64 Gb RAM and RTX4070.

The crash report screen not working ( After crash ).

![image](https://github.com/user-attachments/assets/f89a6161-495b-4ca5-a7f0-c31d486c468e)

### Steps to reproduce behavior

1.) Open HS using the Deck tracker
2.) Start the Battlegrounds game
3.) Play for a while until the Deck tracker stop working ( In game visuals stuck )

### Log/Screenshots

Crash report
```
########## 12/8/2024 10:43:06 AM ##########
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Logfile: C:\Users\\AppData\Roaming\HearthstoneDeckTracker\Logs\hdt_log.txt
```

HDT log
```
9:39:24 AM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
9:39:25 AM|Info|Core.Initialize >> HDT: 1.37.5.6952, Operating System: Windows 10 Home 26100, .NET Framework: 533320
9:39:25 AM|Info|Updater.StartupUpdateCheck >> Checking for updates, using 0
9:39:27 AM|Warning|Updater.StartupUpdateCheck >> UpdateManager init took longer than 2000ms, showing app
9:39:27 AM|Info|ThemeManager.LoadThemes >> Found theme: classic
9:39:27 AM|Info|ThemeManager.LoadThemes >> Found theme: dark
9:39:27 AM|Info|ThemeManager.LoadThemes >> Found theme: frost
9:39:27 AM|Info|ThemeManager.LoadThemes >> Found theme: minimal
9:39:27 AM|Info|GameV2.Reset >> -------- Reset ---------
9:39:28 AM|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
9:39:28 AM|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
9:39:28 AM|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
9:39:28 AM|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
9:39:28 AM|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
9:39:28 AM|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
9:39:28 AM|Info|OverlayWindow.SetTopmost >> Hearthstone window not found
9:39:29 AM|Info|GameV2.Reset >> -------- Reset ---------
9:39:30 AM|Info|BackupManager.Run >> Running BackupManager
9:39:30 AM|Info|BackupManager.Run >> Backup for today already exists
9:39:30 AM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
9:39:30 AM|Info|LogWatcherManager.Start >> Using Hearthstone log directory 'C:\Program Files (x86)\Hearthstone\Logs'
9:39:30 AM|Info|ApiWrapper.UpdateUploadTokenStatus >> Checking token status...
9:39:30 AM|Info|Helper.EnsureClientLogConfig >> client.config is up-to-date
9:39:30 AM|Info|SquirrelConnection.FindBestRemote >> Testing Squirrel Remotes...
9:39:30 AM|Info|HsReplayDecks.Load >> Loaded from disk: Count=2979, ServerTS=12/7/2024 4:44:23 AM, Downloaded=12/7/2024 5:00:13 PM Age=16:39:16.8196038
9:39:30 AM|Info|HsReplayDecks.Load >> Complete: Count=2979, ServerTS=12/7/2024 4:44:23 AM, Downloaded=12/7/2024 5:00:13 PM Age=16:39:16.8196038
9:39:30 AM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
9:39:30 AM|Info|ApiWrapper.UpdateUploadTokenStatus >> Token is not claimed
9:39:31 AM|Info|SquirrelConnection.FindBestRemote >> Test Completed
9:39:31 AM|Info|SquirrelConnection.FindBestRemote >> | Github: 823ms (current)
9:39:31 AM|Info|SquirrelConnection.FindBestRemote >> | AwsHongKong: 1196ms
9:39:31 AM|Info|SquirrelConnection.FindBestRemote >> Github looks good. Using Github.
9:39:31 AM|Info|Updater.SquirrelUpdate >> No new update available
9:40:05|Info|TrackerPlugins.ButtonOpenPluginsFolder_OnClick >> [Helper.TryOpenUrl] C:\Users\Jakub\AppData\Roaming\HearthstoneDeckTracker\Plugins
9:42:29|Info|MainWindow.Window_Closing >> Shutting down...
9:42:29|Error|PluginWrapper.Unload >> HDTBuddyDisplay:
System.NullReferenceException: Object reference not set to an instance of an object.
   at HDTBuddyDisplay.BuddyDisplayPlugin.OnUnload()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Unload() in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Plugins\PluginWrapper.cs:line 168
```

**Comment by VanyaVel** [comment]
A similar problem, has there been a solution or a temporary solution?

**Comment by beheh** [comment]
Duplicate of #4601

**Comment by beheh** [comment]
Please check #4601, I'm uploading a test build there that might fix this issue.
